XMC4500 Barebone Template: inc/3Daccel_out_library.h File Reference
3Daccel_out_library.h File Reference
3Daccel out library header
#include "3Daccel_app.h"
Functions
void initGlobals ()
init global variables
void protocolComplete (int16_t position6D, int16_t positionX, int16_t positionY, int16_t positionZ, uint8_t temperature)
send data to PC and GUI
void outputInit (void)
function to init LED output
void ledSetting (uint8_t ledState)
function to set LED
void getDouble (char *input, double *numDouble)
safe function to make double value from string
void SysTick_Handler (void)
SysTick.
void pwmAngleCalc (int16_t positionX, int16_t positionY, int16_t positionZ)
function to calculate all angles and PWM signal in percent
uint8_t circularAdd (uint8_t item)
add element to circular buffer
uint8_t circularGet (uint8_t *pItem)
read element from circular buffer
void readButtonDebounce ()
read buttons debounce
void inputInit ()
intialize input GPIOs
Detailed Description
3Daccel out library header
Version
v1.0
Date
Nov 2017
Author
Egermann, Resch
Definition in file 3Daccel_out_library.h.
Function Documentation
circularAdd()
uint8_t circularAdd (uint8_t item)
add element to circular buffer
Parameters
8 bit value for buffer
Returns
1 if OK, 0 if KO
Definition at line 350 of file 3Daccel_out_library.c.
References cb, CBSIZE, empty, full, inix, and outix.
Referenced by readButtonDebounce().
 {
     if (full)
     {
         return 0;
     }
     inix = (inix + 1) % CBSIZE;
     cb[inix] = item;
     if (inix == outix)
     {
         full = 1;
     }
     empty = 0;
     return 1;
 }
circularGet()
uint8_t circularGet (uint8_t * pItem)
read element from circular buffer
Parameters
pointer to the 8-bit value
Returns
1 if OK, 0 if KO
Definition at line 371 of file 3Daccel_out_library.c.
References cb, CBSIZE, empty, full, inix, and outix.
Referenced by SysTick_Handler().
 {
     if (empty)
     {
         return 0;
     }
     outix = (outix + 1) % CBSIZE;
     *pItem = cb[outix];
     if (outix == inix)
     {
         empty = 1;
     }
     full = 0;
     return 1;
 }
getDouble()
void getDouble (char * input, double * numDouble)
safe function to make double value from string
Parameters
input string
output double
Returns
none
Definition at line 135 of file 3Daccel_out_library.c.
 {
     long double number = 0;
     char *pointToEnd = NULL;
     number = strtod(input, &pointToEnd);
     if(*pointToEnd != '\0')
     {
         return;
     }
     else
     {
         *numDouble = (double)number;
     }
 }
initGlobals()
void initGlobals ()
init global variables
Parameters
none
Returns
none
Definition at line 18 of file 3Daccel_out_library.c.
References axesRawdata::axisX, axesRawdata::axisY, axesRawdata::axisZ, button1pressed, button2pressed, buttonSend, direction, empty, errorcount, full, inix, old_position, outix, packagesSent, position, readAxes, servoEnable, signal1, signal2, statisticSend, and temperature.
Referenced by main().
 {
     readAxes.axisX = 0;
     readAxes.axisY = 0;
     readAxes.axisZ = 0;
     direction = 6;
     temperature = 0;
     errorcount = 0;
     packagesSent = 0;
     position = 0;
     old_position = 0;
     signal1 = 0.00;
     signal2 = 0.00;
     button1pressed = 0;
     button2pressed = 0;
     statisticSend = 0;
     servoEnable = 0;
     buttonSend = 0;
     inix = 0;
     outix = 0;
     full = 0;
     empty = 1;
 }
inputInit()
void inputInit ()
intialize input GPIOs
Parameters
none
Returns
none
Definition at line 337 of file 3Daccel_out_library.c.
References BUTTON1, and BUTTON2.
Referenced by main().
 {
     XMC_GPIO_CONFIG_t config_in;
     config_in.mode = XMC_GPIO_MODE_INPUT_INVERTED_PULL_UP;
     XMC_GPIO_Init(BUTTON1, &config_in);
     XMC_GPIO_Init(BUTTON2, &config_in);
 }
ledSetting()
void ledSetting (uint8_t ledState)
function to set LED
Parameters
LED state
0 for LED off
1 for LED on
other for LED toggle
Returns
none
Definition at line 175 of file 3Daccel_out_library.c.
References LED1.
Referenced by main(), and protocolComplete().
 {
     if (ledState == 0)
     {
         XMC_GPIO_SetOutputLow(XMC_GPIO_PORT1, 0);
     }
     else if (ledState == 1)
     {
         XMC_GPIO_SetOutputHigh(XMC_GPIO_PORT1, 0);
     }
     else
     {
         XMC_GPIO_ToggleOutput(LED1);
     }
 }
outputInit()
void outputInit (void)
function to init LED output
Parameters
none
Returns
none
Definition at line 157 of file 3Daccel_out_library.c.
References LED1.
Referenced by main().
 {
     XMC_GPIO_CONFIG_t config_out;
     config_out.mode = XMC_GPIO_MODE_OUTPUT_PUSH_PULL;
     config_out.output_level = XMC_GPIO_OUTPUT_LEVEL_LOW;
     config_out.output_strength = XMC_GPIO_OUTPUT_STRENGTH_WEAK;
     XMC_GPIO_Init(LED1, &config_out);
 }
protocolComplete()
void protocolComplete (int16_t position6D, int16_t positionX, int16_t positionY, int16_t positionZ, uint8_t temperature)
send data to PC and GUI
Parameters
6D position
raw X acceleration value
raw Y acceleration value
raw Z acceleration value
temperature value
Returns
none
Definition at line 52 of file 3Daccel_out_library.c.
References _uart_printf(), buttonSend, errorcount, ledSetting(), packagesSent, RXBUFFERSIZE, and statisticSend.
Referenced by main().
 {
     char string6D[8][6] = {"#USX,", "#UDX,", "#DSX,", "#DDX,", "#TOP,", "#BOT,", "#XXX,", "#FAL,"};
     char send[RXBUFFERSIZE];
     memset (&send, 0, sizeof (send));
     if (statisticSend == 1)
     {
         if (sprintf(send, "#STA,%10lu,%3d$\n", packagesSent, errorcount) < 0)
         {
             errorcount++;
         }
         else
         {
 #if DEBUG
             printf("send %s", send);
 #endif
             _uart_printf("%s", send);
             packagesSent++;
         }
         statisticSend = 0;
         return;
     }
     else if (buttonSend == 1)
     {
         if (sprintf(send, "#BUT,1$\n") < 0)
         {
             errorcount++;
         }
         else
         {
 #if DEBUG
             printf("send %s", send);
 #endif
             _uart_printf("%s", send);
             packagesSent++;
         }
         buttonSend = 0;
         return;
     }
     else if (buttonSend == 2)
     {
         if (sprintf(send, "#BUT,2$\n") < 0)
         {
             errorcount++;
         }
         else
         {
 #if DEBUG
             printf("send %s", send);
 #endif
             _uart_printf("%s", send);
             packagesSent++;
         }
         buttonSend = 0;
         return;
     }
     else
     {
         if (sprintf(send, "%s%7d%s%7d%s%7d%s%02d$\n", string6D[position6D], positionX, ",", positionY, ",", positionZ, ",", temperature* 2 + 6) < 0)
         {
             errorcount++;
         }
         else
         {
 #if DEBUG
             printf("send %s", send);
 #endif
             _uart_printf("%s", send);
             ledSetting(3);
             packagesSent++;
         }
     }
 }
pwmAngleCalc()
void pwmAngleCalc (int16_t positionX, int16_t positionY, int16_t positionZ)
function to calculate all angles and PWM signal in percent
Parameters
raw X acceleration value
raw Y acceleration value
raw Z acceleration value
Returns
none
Definition at line 199 of file 3Daccel_out_library.c.
References GDIVIDER, PI, SERUPLO0, SERVOLO0, SERVOLOLINEAR, SERVOUOLINEAR, signal1, and signal2.
Referenced by SysTick_Handler().
 {
     double pi = PI;
     double divider = GDIVIDER;
     double roll, pitch;
     double gX, gY, gZ;
     gX = positionX / divider;
     gY = positionY / divider;
     gZ = positionZ / divider;
     roll = atan(gY/(sqrt((gX*gX)+(gZ*gZ)))) * 180 / pi;
     pitch = atan(gX/(sqrt((gY*gY)+(gZ*gZ)))) * 180 / pi;
     signal1 = (90.00+roll) * SERVOUOLINEAR + SERUPLO0;
     signal2 = (90.00+pitch) * SERVOLOLINEAR + SERVOLO0;
     signal1 = (int)(signal1 * 1000 + 0.5) / 1000.0;
     signal2 = (int)(signal2 * 1000 + 0.5) / 1000.0;
 }
readButtonDebounce()
void readButtonDebounce ()
read buttons debounce
Parameters
none
Returns
none
Definition at line 296 of file 3Daccel_out_library.c.
References BUTTON1, BUTTON1INT, button1pressed, BUTTON2, BUTTON2INT, button2pressed, and circularAdd().
Referenced by SysTick_Handler().
 {
     if ((XMC_GPIO_GetInput(BUTTON1) == 0) && (button1pressed == 0))
     {
         button1pressed = 1;
     }
     if ((XMC_GPIO_GetInput(BUTTON1) == 0) && (button1pressed == 1))
     {
         button1pressed = 2;
     }
     if ((XMC_GPIO_GetInput(BUTTON1) == 1) && (button1pressed == 2))
     {
         if (circularAdd(BUTTON1INT) == 1)
         {
             button1pressed = 0;
         }
     }
     if ((XMC_GPIO_GetInput(BUTTON2) == 0) && (button2pressed == 0))
     {
         button2pressed = 1;
     }
     if ((XMC_GPIO_GetInput(BUTTON2) == 0) && (button2pressed == 1))
     {
         button2pressed = 2;
     }
     if ((XMC_GPIO_GetInput(BUTTON2) == 1) && (button2pressed == 2))
     {
         if (circularAdd(BUTTON2INT) == 1)
         {
             button2pressed = 0;
         }
     }
 }
SysTick_Handler()
void SysTick_Handler (void)
SysTick.
Parameters
none
Returns
none
Definition at line 226 of file 3Daccel_out_library.c.
References axesRawdata::axisX, axesRawdata::axisY, axesRawdata::axisZ, BUTTON1INT, BUTTON2INT, buttonSend, circularGet(), direction, get6Dposition(), getAxesRawData(), getTemperature(), pwm(), pwmAngleCalc(), readAxes, readButtonDebounce(), SENSORTICKS, servoEnable, SERVOLOCENTER, SERVOUPCENTER, signal1, signal2, and temperature.
 {
     static uint32_t ticks = 0;
     static uint8_t buttonIDpressed;
     readButtonDebounce();
     if (circularGet(&buttonIDpressed))
     {
         switch (buttonIDpressed)
         {
             case BUTTON1INT:
             {
 #if DEBUG
                 printf("button 1 pressed\n");
 #endif
                 buttonSend = 1;
                 break;
             }
             case BUTTON2INT:
             {
 #if DEBUG
                 printf("button 2 pressed\n");
 #endif
                 buttonSend = 2;
                 break;
             }
             default:
             {
                 buttonSend = 0;
                 break;
             }
         }
     }
     ticks++;
     if(ticks == SENSORTICKS)
     {
         // get temperature
         temperature = getTemperature(&temperature);
         // get 6D Position
         direction = get6Dposition();
         // get raw data
         readAxes = getAxesRawData();
         // calculate servo output
         pwmAngleCalc(readAxes.axisX, readAxes.axisY, readAxes.axisZ);
         ticks = 0;
     }
     if (servoEnable == 1)
     {
         // set servo
         pwm(signal1, 0);
         pwm(signal2, 1);
     }
     else
     {
         pwm(SERVOUPCENTER, 0);
         pwm(SERVOLOCENTER, 1);
     }
 }