BEL3 ESS task: src/lis3dh_driver.c File Reference
lis3dh_driver.c File Reference
lis3dh driver
#include "lis3dh_driver.h"
Functions
u8_t LIS3DH_ReadReg (u8_t Reg, u8_t *Data)
u8_t LIS3DH_WriteReg (u8_t WriteAddr, u8_t Data)
status_t LIS3DH_GetWHO_AM_I (u8_t *val)
status_t LIS3DH_GetStatusAUX (u8_t *val)
status_t LIS3DH_GetStatusAUXBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_SetODR (LIS3DH_ODR_t ov)
status_t LIS3DH_SetTemperature (State_t state)
status_t LIS3DH_SetADCAux (State_t state)
status_t LIS3DH_GetAuxRaw (LIS3DH_Aux123Raw_t *buff)
status_t LIS3DH_GetTempRaw (i8_t *buff)
status_t LIS3DH_SetMode (LIS3DH_Mode_t md)
status_t LIS3DH_SetAxis (LIS3DH_Axis_t axis)
status_t LIS3DH_SetFullScale (LIS3DH_Fullscale_t fs)
status_t LIS3DH_SetBDU (State_t bdu)
status_t LIS3DH_SetBLE (LIS3DH_Endianess_t ble)
status_t LIS3DH_SetSelfTest (LIS3DH_SelfTest_t st)
status_t LIS3DH_HPFClickEnable (State_t hpfe)
status_t LIS3DH_HPFAOI1Enable (State_t hpfe)
status_t LIS3DH_HPFAOI2Enable (State_t hpfe)
status_t LIS3DH_SetHPFMode (LIS3DH_HPFMode_t hpm)
status_t LIS3DH_SetHPFCutOFF (LIS3DH_HPFCutOffFreq_t hpf)
status_t LIS3DH_SetFilterDataSel (State_t state)
status_t LIS3DH_SetInt1Pin (LIS3DH_IntPinConf_t pinConf)
status_t LIS3DH_SetInt2Pin (LIS3DH_IntPinConf_t pinConf)
status_t LIS3DH_SetClickCFG (u8_t status)
status_t LIS3DH_SetClickTHS (u8_t ths)
status_t LIS3DH_SetClickLIMIT (u8_t t_limit)
status_t LIS3DH_SetClickLATENCY (u8_t t_latency)
status_t LIS3DH_SetClickWINDOW (u8_t t_window)
status_t LIS3DH_GetClickResponse (u8_t *res)
status_t LIS3DH_Int1LatchEnable (State_t latch)
status_t LIS3DH_ResetInt1Latch (void)
status_t LIS3DH_SetIntConfiguration (LIS3DH_Int1Conf_t ic)
status_t LIS3DH_SetIntMode (LIS3DH_Int1Mode_t int_mode)
status_t LIS3DH_SetInt6D4DConfiguration (LIS3DH_INT_6D_4D_t ic)
status_t LIS3DH_Get6DPosition (u8_t *val)
status_t LIS3DH_SetInt1Threshold (u8_t ths)
status_t LIS3DH_SetInt1Duration (LIS3DH_Int1Conf_t id)
status_t LIS3DH_FIFOModeEnable (LIS3DH_FifoMode_t fm)
status_t LIS3DH_SetTriggerInt (LIS3DH_TrigInt_t tr)
status_t LIS3DH_SetWaterMark (u8_t wtm)
status_t LIS3DH_GetStatusReg (u8_t *val)
status_t LIS3DH_GetStatusBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_GetAccAxesRaw (AxesRaw_t *buff)
status_t LIS3DH_GetInt1Src (u8_t *val)
status_t LIS3DH_GetInt1SrcBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_GetFifoSourceReg (u8_t *val)
status_t LIS3DH_GetFifoSourceBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_GetFifoSourceFSS (u8_t *val)
status_t LIS3DH_SetSPIInterface (LIS3DH_SPIMode_t spi)
Detailed Description
lis3dh driver
Version
x
Date
x
Author
STMicroelectronics
Definition in file lis3dh_driver.c.
Function Documentation
LIS3DH_FIFOModeEnable()
status_t LIS3DH_FIFOModeEnable (LIS3DH_FifoMode_t fm)
Definition at line 1133 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG5, LIS3DH_FIFO_BYPASS_MODE, LIS3DH_FIFO_CTRL_REG, LIS3DH_FIFO_DISABLE, LIS3DH_FIFO_EN, LIS3DH_FIFO_MODE, LIS3DH_FIFO_STREAM_MODE, LIS3DH_FIFO_TRIGGER_MODE, LIS3DH_FM, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, MEMS_SET, and MEMS_SUCCESS.
{
     u8_t value;
     if(fm == LIS3DH_FIFO_DISABLE) {
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1F;
         value |= (LIS3DH_FIFO_BYPASS_MODE<<LIS3DH_FM);
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )           //fifo mode bypass
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo disable
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_BYPASS_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                     //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                      //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_STREAM_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                      //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_TRIGGER_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                      //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     return MEMS_SUCCESS;
 }
LIS3DH_Get6DPosition()
status_t LIS3DH_Get6DPosition (u8_t * val)
Definition at line 1055 of file lis3dh_driver.c.
References LIS3DH_BOTTOM, LIS3DH_DW_DX, LIS3DH_DW_SX, LIS3DH_INT1_SRC, LIS3DH_ReadReg(), LIS3DH_TOP, LIS3DH_UP_DX, LIS3DH_UP_SX, MEMS_ERROR, and MEMS_SUCCESS.
Referenced by get6Dposition().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     switch (value) {
     case LIS3DH_UP_SX:
         *val = LIS3DH_UP_SX;
         break;
     case LIS3DH_UP_DX:
         *val = LIS3DH_UP_DX;
         break;
     case LIS3DH_DW_SX:
         *val = LIS3DH_DW_SX;
         break;
     case LIS3DH_DW_DX:
         *val = LIS3DH_DW_DX;
         break;
     case LIS3DH_TOP:
         *val = LIS3DH_TOP;
         break;
     case LIS3DH_BOTTOM:
         *val = LIS3DH_BOTTOM;
         break;
     }
     return MEMS_SUCCESS;
 }
LIS3DH_GetAccAxesRaw()
status_t LIS3DH_GetAccAxesRaw (AxesRaw_t * buff)
Definition at line 1400 of file lis3dh_driver.c.
References AxesRaw_t::AXIS_X, AxesRaw_t::AXIS_Y, AxesRaw_t::AXIS_Z, LIS3DH_OUT_X_H, LIS3DH_OUT_X_L, LIS3DH_OUT_Y_H, LIS3DH_OUT_Y_L, LIS3DH_OUT_Z_H, LIS3DH_OUT_Z_L, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by getAxesRawData().
{
     i16_t value;
     u8_t *valueL = (u8_t *)(&value);
     u8_t *valueH = ((u8_t *)(&value)+1);
     if( !LIS3DH_ReadReg(LIS3DH_OUT_X_L, valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_X_H, valueH) )
         return MEMS_ERROR;
     buff->AXIS_X = value;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Y_L, valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Y_H, valueH) )
         return MEMS_ERROR;
     buff->AXIS_Y = value;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Z_L, valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Z_H, valueH) )
         return MEMS_ERROR;
     buff->AXIS_Z = value;
     return MEMS_SUCCESS;
 }
LIS3DH_GetAuxRaw()
status_t LIS3DH_GetAuxRaw (LIS3DH_Aux123Raw_t * buff)
Definition at line 304 of file lis3dh_driver.c.
References LIS3DH_Aux123Raw_t::AUX_1, LIS3DH_Aux123Raw_t::AUX_2, LIS3DH_Aux123Raw_t::AUX_3, LIS3DH_OUT_1_H, LIS3DH_OUT_1_L, LIS3DH_OUT_2_H, LIS3DH_OUT_2_L, LIS3DH_OUT_3_H, LIS3DH_OUT_3_L, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t valueL;
     u8_t valueH;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_1_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_1_H, &valueH) )
         return MEMS_ERROR;
     buff->AUX_1 = (u16_t)( (valueH << 8) | valueL )/16;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_2_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_2_H, &valueH) )
         return MEMS_ERROR;
     buff->AUX_2 = (u16_t)( (valueH << 8) | valueL )/16;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_H, &valueH) )
         return MEMS_ERROR;
     buff->AUX_3 = (u16_t)( (valueH << 8) | valueL )/16;
     return MEMS_SUCCESS;
 }
LIS3DH_GetClickResponse()
status_t LIS3DH_GetClickResponse (u8_t * res)
Definition at line 836 of file lis3dh_driver.c.
References LIS3DH_CLICK_SIGN, LIS3DH_CLICK_SRC, LIS3DH_CLICK_X, LIS3DH_CLICK_Y, LIS3DH_CLICK_Z, LIS3DH_DCLICK, LIS3DH_DCLICK_X_N, LIS3DH_DCLICK_X_P, LIS3DH_DCLICK_Y_N, LIS3DH_DCLICK_Y_P, LIS3DH_DCLICK_Z_N, LIS3DH_DCLICK_Z_P, LIS3DH_IA, LIS3DH_NO_CLICK, LIS3DH_ReadReg(), LIS3DH_SCLICK_X_N, LIS3DH_SCLICK_X_P, LIS3DH_SCLICK_Y_N, LIS3DH_SCLICK_Y_P, LIS3DH_SCLICK_Z_N, LIS3DH_SCLICK_Z_P, MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CLICK_SRC, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     if((value & LIS3DH_IA)==0) {
         *res = LIS3DH_NO_CLICK;
         return MEMS_SUCCESS;
     }
     else {
         if (value & LIS3DH_DCLICK) {
             if (value & LIS3DH_CLICK_SIGN) {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_DCLICK_Z_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_DCLICK_Y_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_DCLICK_X_N;
                     return MEMS_SUCCESS;
                 }
             }
             else {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_DCLICK_Z_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_DCLICK_Y_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_DCLICK_X_P;
                     return MEMS_SUCCESS;
                 }
             }
         }
         else {
             if (value & LIS3DH_CLICK_SIGN) {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_SCLICK_Z_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_SCLICK_Y_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_SCLICK_X_N;
                     return MEMS_SUCCESS;
                 }
             }
             else {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_SCLICK_Z_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_SCLICK_Y_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_SCLICK_X_P;
                     return MEMS_SUCCESS;
                 }
             }
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetFifoSourceBit()
status_t LIS3DH_GetFifoSourceBit (u8_t statusBIT, u8_t * val)
Definition at line 1566 of file lis3dh_driver.c.
References LIS3DH_FIFO_SRC_EMPTY, LIS3DH_FIFO_SRC_OVRUN, LIS3DH_FIFO_SRC_REG, LIS3DH_FIFO_SRC_WTM, LIS3DH_ReadReg(), MEMS_ERROR, MEMS_RESET, MEMS_SET, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_SRC_REG, &value) )
         return MEMS_ERROR;
     if(statusBIT == LIS3DH_FIFO_SRC_WTM) {
         if(value &= LIS3DH_FIFO_SRC_WTM) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_FIFO_SRC_OVRUN) {
         if(value &= LIS3DH_FIFO_SRC_OVRUN) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_FIFO_SRC_EMPTY) {
         if(value &= statusBIT == LIS3DH_FIFO_SRC_EMPTY) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetFifoSourceFSS()
status_t LIS3DH_GetFifoSourceFSS (u8_t * val)
Definition at line 1615 of file lis3dh_driver.c.
References LIS3DH_FIFO_SRC_REG, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_SRC_REG, &value) )
         return MEMS_ERROR;
     value &= 0x1F;
     *val = value;
     return MEMS_SUCCESS;
 }
LIS3DH_GetFifoSourceReg()
status_t LIS3DH_GetFifoSourceReg (u8_t * val)
Definition at line 1549 of file lis3dh_driver.c.
References LIS3DH_FIFO_SRC_REG, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_SRC_REG, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetInt1Src()
status_t LIS3DH_GetInt1Src (u8_t * val)
Definition at line 1440 of file lis3dh_driver.c.
References LIS3DH_INT1_SRC, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetInt1SrcBit()
status_t LIS3DH_GetInt1SrcBit (u8_t statusBIT, u8_t * val)
Definition at line 1457 of file lis3dh_driver.c.
References LIS3DH_INT1_SRC, LIS3DH_INT1_SRC_IA, LIS3DH_INT1_SRC_XH, LIS3DH_INT1_SRC_XL, LIS3DH_INT1_SRC_YH, LIS3DH_INT1_SRC_YL, LIS3DH_INT1_SRC_ZH, LIS3DH_INT1_SRC_ZL, LIS3DH_ReadReg(), MEMS_ERROR, MEMS_RESET, MEMS_SET, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, &value) )
         return MEMS_ERROR;
     if(statusBIT == LIS3DH_INT1_SRC_IA) {
         if(value &= LIS3DH_INT1_SRC_IA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_ZH) {
         if(value &= LIS3DH_INT1_SRC_ZH) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_ZL) {
         if(value &= LIS3DH_INT1_SRC_ZL) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_YH) {
         if(value &= LIS3DH_INT1_SRC_YH) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_YL) {
         if(value &= LIS3DH_INT1_SRC_YL) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_XH) {
         if(value &= LIS3DH_INT1_SRC_XH) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_XL) {
         if(value &= LIS3DH_INT1_SRC_XL) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetStatusAUX()
status_t LIS3DH_GetStatusAUX (u8_t * val)
Definition at line 111 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_STATUS_AUX, MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_AUX, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetStatusAUXBit()
status_t LIS3DH_GetStatusAUXBit (u8_t statusBIT, u8_t * val)
Definition at line 129 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_STATUS_AUX, LIS3DH_STATUS_AUX_1DA, LIS3DH_STATUS_AUX_1OR, LIS3DH_STATUS_AUX_2DA, LIS3DH_STATUS_AUX_2OR, LIS3DH_STATUS_AUX_321DA, LIS3DH_STATUS_AUX_321OR, LIS3DH_STATUS_AUX_3DA, LIS3DH_STATUS_AUX_3OR, MEMS_ERROR, MEMS_RESET, MEMS_SET, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_AUX, &value) )
         return MEMS_ERROR;
     if(statusBIT == LIS3DH_STATUS_AUX_321OR) {
         if(value &= LIS3DH_STATUS_AUX_321OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_3OR) {
         if(value &= LIS3DH_STATUS_AUX_3OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_2OR) {
         if(value &= LIS3DH_STATUS_AUX_2OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_1OR) {
         if(value &= LIS3DH_STATUS_AUX_1OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_321DA) {
         if(value &= LIS3DH_STATUS_AUX_321DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_3DA) {
         if(value &= LIS3DH_STATUS_AUX_3DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_2DA) {
         if(value &= LIS3DH_STATUS_AUX_2DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_1DA) {
         if(value &= LIS3DH_STATUS_AUX_1DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetStatusBit()
status_t LIS3DH_GetStatusBit (u8_t statusBIT, u8_t * val)
Definition at line 1308 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_STATUS_REG, LIS3DH_STATUS_REG_XDA, LIS3DH_STATUS_REG_XOR, LIS3DH_STATUS_REG_YDA, LIS3DH_STATUS_REG_YOR, LIS3DH_STATUS_REG_ZDA, LIS3DH_STATUS_REG_ZOR, LIS3DH_STATUS_REG_ZYXDA, LIS3DH_STATUS_REG_ZYXOR, MEMS_ERROR, MEMS_RESET, MEMS_SET, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_REG, &value) )
         return MEMS_ERROR;
     switch (statusBIT) {
     case LIS3DH_STATUS_REG_ZYXOR:
         if(value &= LIS3DH_STATUS_REG_ZYXOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_ZOR:
         if(value &= LIS3DH_STATUS_REG_ZOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_YOR:
         if(value &= LIS3DH_STATUS_REG_YOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_XOR:
         if(value &= LIS3DH_STATUS_REG_XOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_ZYXDA:
         if(value &= LIS3DH_STATUS_REG_ZYXDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_ZDA:
         if(value &= LIS3DH_STATUS_REG_ZDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_YDA:
         if(value &= LIS3DH_STATUS_REG_YDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_XDA:
         if(value &= LIS3DH_STATUS_REG_XDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetStatusReg()
status_t LIS3DH_GetStatusReg (u8_t * val)
Definition at line 1290 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_STATUS_REG, MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_REG, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetTempRaw()
status_t LIS3DH_GetTempRaw (i8_t * buff)
Definition at line 343 of file lis3dh_driver.c.
References LIS3DH_OUT_3_H, LIS3DH_OUT_3_L, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t valueL;
     u8_t valueH;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_H, &valueH) )
         return MEMS_ERROR;
     *buff = (i8_t)( valueH );
     return MEMS_SUCCESS;
 }
LIS3DH_GetWHO_AM_I()
status_t LIS3DH_GetWHO_AM_I (u8_t * val)
Definition at line 95 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_WHO_AM_I, MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_ReadReg(LIS3DH_WHO_AM_I, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_HPFAOI1Enable()
status_t LIS3DH_HPFAOI1Enable (State_t hpfe)
Definition at line 559 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPIS1, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xFE;
     value |= (hpfe<<LIS3DH_HPIS1);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_HPFAOI2Enable()
status_t LIS3DH_HPFAOI2Enable (State_t hpfe)
Definition at line 582 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPIS2, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xFD;
     value |= (hpfe<<LIS3DH_HPIS2);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_HPFClickEnable()
status_t LIS3DH_HPFClickEnable (State_t hpfe)
Definition at line 536 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPCLICK, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xFB;
     value |= (hpfe<<LIS3DH_HPCLICK);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_Int1LatchEnable()
status_t LIS3DH_Int1LatchEnable (State_t latch)
Definition at line 921 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG5, LIS3DH_LIR_INT1, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
         return MEMS_ERROR;
     value &= 0xF7;
     value |= latch<<LIS3DH_LIR_INT1;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_ReadReg()
u8_t LIS3DH_ReadReg (u8_t Reg, u8_t * Data)
Definition at line 52 of file lis3dh_driver.c.
References _i2c_xfer().
Referenced by LIS3DH_FIFOModeEnable(), LIS3DH_Get6DPosition(), LIS3DH_GetAccAxesRaw(), LIS3DH_GetAuxRaw(), LIS3DH_GetClickResponse(), LIS3DH_GetFifoSourceBit(), LIS3DH_GetFifoSourceFSS(), LIS3DH_GetFifoSourceReg(), LIS3DH_GetInt1Src(), LIS3DH_GetInt1SrcBit(), LIS3DH_GetStatusAUX(), LIS3DH_GetStatusAUXBit(), LIS3DH_GetStatusBit(), LIS3DH_GetStatusReg(), LIS3DH_GetTempRaw(), LIS3DH_GetWHO_AM_I(), LIS3DH_HPFAOI1Enable(), LIS3DH_HPFAOI2Enable(), LIS3DH_HPFClickEnable(), LIS3DH_Int1LatchEnable(), LIS3DH_ResetInt1Latch(), LIS3DH_SetADCAux(), LIS3DH_SetAxis(), LIS3DH_SetBDU(), LIS3DH_SetBLE(), LIS3DH_SetClickCFG(), LIS3DH_SetFilterDataSel(), LIS3DH_SetFullScale(), LIS3DH_SetHPFCutOFF(), LIS3DH_SetHPFMode(), LIS3DH_SetInt1Pin(), LIS3DH_SetInt2Pin(), LIS3DH_SetInt6D4DConfiguration(), LIS3DH_SetIntConfiguration(), LIS3DH_SetIntMode(), LIS3DH_SetMode(), LIS3DH_SetODR(), LIS3DH_SetSelfTest(), LIS3DH_SetSPIInterface(), LIS3DH_SetTemperature(), LIS3DH_SetTriggerInt(), and LIS3DH_SetWaterMark().
{
     //To be completed with either I2c or SPI reading function
     //i.e. *Data = SPI_Mems_Read_Reg( Reg );
     // added i2c xfer function FHTW
     *Data = _i2c_xfer (0, Reg, 0, 1);
     return 1;
 }
LIS3DH_ResetInt1Latch()
status_t LIS3DH_ResetInt1Latch (void)
Definition at line 944 of file lis3dh_driver.c.
References LIS3DH_INT1_SRC, LIS3DH_ReadReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, &value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetADCAux()
status_t LIS3DH_SetADCAux (State_t state)
Definition at line 281 of file lis3dh_driver.c.
References LIS3DH_ADC_PD, LIS3DH_ReadReg(), LIS3DH_TEMP_CFG_REG, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_TEMP_CFG_REG, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     value |= state<<LIS3DH_ADC_PD;
     if( !LIS3DH_WriteReg(LIS3DH_TEMP_CFG_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetAxis()
status_t LIS3DH_SetAxis (LIS3DH_Axis_t axis)
Definition at line 423 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG1, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by initMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG1, &value) )
         return MEMS_ERROR;
     value &= 0xF8;
     value |= (0x07 & axis);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG1, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetBDU()
status_t LIS3DH_SetBDU (State_t bdu)
Definition at line 468 of file lis3dh_driver.c.
References LIS3DH_BDU, LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     value |= (bdu<<LIS3DH_BDU);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetBLE()
status_t LIS3DH_SetBLE (LIS3DH_Endianess_t ble)
Definition at line 491 of file lis3dh_driver.c.
References LIS3DH_BLE, LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xBF;
     value |= (ble<<LIS3DH_BLE);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetClickCFG()
status_t LIS3DH_SetClickCFG (u8_t status)
Definition at line 743 of file lis3dh_driver.c.
References LIS3DH_CLICK_CFG, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CLICK_CFG, &value) )
         return MEMS_ERROR;
     value &= 0xC0;
     value |= status;
     if( !LIS3DH_WriteReg(LIS3DH_CLICK_CFG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetClickLATENCY()
status_t LIS3DH_SetClickLATENCY (u8_t t_latency)
Definition at line 804 of file lis3dh_driver.c.
References LIS3DH_TIME_LATENCY, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_WriteReg(LIS3DH_TIME_LATENCY, t_latency) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetClickLIMIT()
status_t LIS3DH_SetClickLIMIT (u8_t t_limit)
Definition at line 785 of file lis3dh_driver.c.
References LIS3DH_TIME_LIMIT, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if(t_limit>127)
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_TIME_LIMIT, t_limit) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetClickTHS()
status_t LIS3DH_SetClickTHS (u8_t ths)
Definition at line 766 of file lis3dh_driver.c.
References LIS3DH_CLICK_THS, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if(ths>127)
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_CLICK_THS, ths) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetClickWINDOW()
status_t LIS3DH_SetClickWINDOW (u8_t t_window)
Definition at line 820 of file lis3dh_driver.c.
References LIS3DH_TIME_WINDOW, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if( !LIS3DH_WriteReg(LIS3DH_TIME_WINDOW, t_window) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetFilterDataSel()
status_t LIS3DH_SetFilterDataSel (State_t state)
Definition at line 656 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_FDS, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xF7;
     value |= (state<<LIS3DH_FDS);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetFullScale()
status_t LIS3DH_SetFullScale (LIS3DH_Fullscale_t fs)
Definition at line 445 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG4, LIS3DH_FS, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by initMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xCF;
     value |= (fs<<LIS3DH_FS);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetHPFCutOFF()
status_t LIS3DH_SetHPFCutOFF (LIS3DH_HPFCutOffFreq_t hpf)
Definition at line 629 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPCF, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if (hpf > 3)
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xCF;
     value |= (hpf<<LIS3DH_HPCF);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetHPFMode()
status_t LIS3DH_SetHPFMode (LIS3DH_HPFMode_t hpm)
Definition at line 606 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPM, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0x3F;
     value |= (hpm<<LIS3DH_HPM);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt1Duration()
status_t LIS3DH_SetInt1Duration (LIS3DH_Int1Conf_t id)
Definition at line 1113 of file lis3dh_driver.c.
References LIS3DH_INT1_DURATION, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     if (id > 127)
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_INT1_DURATION, id) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt1Pin()
status_t LIS3DH_SetInt1Pin (LIS3DH_IntPinConf_t pinConf)
Definition at line 687 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG3, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG3, &value) )
         return MEMS_ERROR;
     value &= 0x00;
     value |= pinConf;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG3, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt1Threshold()
status_t LIS3DH_SetInt1Threshold (u8_t ths)
Definition at line 1095 of file lis3dh_driver.c.
References LIS3DH_INT1_THS, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by configMEMSsensor().
{
     if (ths > 127)
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_INT1_THS, ths) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt2Pin()
status_t LIS3DH_SetInt2Pin (LIS3DH_IntPinConf_t pinConf)
Definition at line 716 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG6, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG6, &value) )
         return MEMS_ERROR;
     value &= 0x00;
     value |= pinConf;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG6, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt6D4DConfiguration()
status_t LIS3DH_SetInt6D4DConfiguration (LIS3DH_INT_6D_4D_t ic)
Definition at line 1009 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG5, LIS3DH_D4D_INT1, LIS3DH_INT1_4D_ENABLE, LIS3DH_INT1_6D_4D_DISABLE, LIS3DH_INT1_6D_ENABLE, LIS3DH_INT1_CFG, LIS3DH_INT_6D, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_DISABLE, MEMS_ENABLE, MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     u8_t value2;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_CFG, &value) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value2) )
         return MEMS_ERROR;
     if(ic == LIS3DH_INT1_6D_ENABLE) {
         value &= 0xBF;
         value |= (MEMS_ENABLE<<LIS3DH_INT_6D);
         value2 &= 0xFB;
         value2 |= (MEMS_DISABLE<<LIS3DH_D4D_INT1);
     }
     if(ic == LIS3DH_INT1_4D_ENABLE) {
         value &= 0xBF;
         value |= (MEMS_ENABLE<<LIS3DH_INT_6D);
         value2 &= 0xFB;
         value2 |= (MEMS_ENABLE<<LIS3DH_D4D_INT1);
     }
     if(ic == LIS3DH_INT1_6D_4D_DISABLE) {
         value &= 0xBF;
         value |= (MEMS_DISABLE<<LIS3DH_INT_6D);
         value2 &= 0xFB;
         value2 |= (MEMS_DISABLE<<LIS3DH_D4D_INT1);
     }
     if( !LIS3DH_WriteReg(LIS3DH_INT1_CFG, value) )
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value2) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetIntConfiguration()
status_t LIS3DH_SetIntConfiguration (LIS3DH_Int1Conf_t ic)
Definition at line 962 of file lis3dh_driver.c.
References LIS3DH_INT1_CFG, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_CFG, &value) )
         return MEMS_ERROR;
     value &= 0x40;
     value |= ic;
     if( !LIS3DH_WriteReg(LIS3DH_INT1_CFG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetIntMode()
status_t LIS3DH_SetIntMode (LIS3DH_Int1Mode_t int_mode)
Definition at line 986 of file lis3dh_driver.c.
References LIS3DH_INT1_CFG, LIS3DH_INT_6D, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_CFG, &value) )
         return MEMS_ERROR;
     value &= 0x3F;
     value |= (int_mode<<LIS3DH_INT_6D);
     if( !LIS3DH_WriteReg(LIS3DH_INT1_CFG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetMode()
status_t LIS3DH_SetMode (LIS3DH_Mode_t md)
Definition at line 366 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG1, LIS3DH_CTRL_REG4, LIS3DH_HR, LIS3DH_LOW_POWER, LIS3DH_LPEN, LIS3DH_NORMAL, LIS3DH_POWER_DOWN, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, MEMS_RESET, MEMS_SET, and MEMS_SUCCESS.
Referenced by initMEMSsensor().
{
     u8_t value;
     u8_t value2;
     static   u8_t ODR_old_value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG1, &value) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value2) )
         return MEMS_ERROR;
     if((value & 0xF0)==0)
         value = value | (ODR_old_value & 0xF0); //if it comes from POWERDOWN
     switch(md) {
     case LIS3DH_POWER_DOWN:
         ODR_old_value = value;
         value &= 0x0F;
         break;
     case LIS3DH_NORMAL:
         value &= 0xF7;
         value |= (MEMS_RESET<<LIS3DH_LPEN);
         value2 &= 0xF7;
         value2 |= (MEMS_SET<<LIS3DH_HR);   //set HighResolution_BIT
         break;
     case LIS3DH_LOW_POWER:
         value &= 0xF7;
         value |=  (MEMS_SET<<LIS3DH_LPEN);
         value2 &= 0xF7;
         value2 |= (MEMS_RESET<<LIS3DH_HR); //reset HighResolution_BIT
         break;
     default:
         return MEMS_ERROR;
     }
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG1, value) )
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value2) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetODR()
status_t LIS3DH_SetODR (LIS3DH_ODR_t ov)
Definition at line 233 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG1, LIS3DH_ODR_BIT, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
Referenced by initMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG1, &value) )
         return MEMS_ERROR;
     value &= 0x0f;
     value |= ov<<LIS3DH_ODR_BIT;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG1, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetSelfTest()
status_t LIS3DH_SetSelfTest (LIS3DH_SelfTest_t st)
Definition at line 513 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), LIS3DH_ST, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xF9;
     value |= (st<<LIS3DH_ST);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetSPIInterface()
status_t LIS3DH_SetSPIInterface (LIS3DH_SPIMode_t spi)
Definition at line 1636 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), LIS3DH_SIM, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xFE;
     value |= spi<<LIS3DH_SIM;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetTemperature()
status_t LIS3DH_SetTemperature (State_t state)
Definition at line 258 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_TEMP_CFG_REG, LIS3DH_TEMP_EN, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_TEMP_CFG_REG, &value) )
         return MEMS_ERROR;
     value &= 0xBF;
     value |= state<<LIS3DH_TEMP_EN;
     if( !LIS3DH_WriteReg(LIS3DH_TEMP_CFG_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetTriggerInt()
status_t LIS3DH_SetTriggerInt (LIS3DH_TrigInt_t tr)
Definition at line 1241 of file lis3dh_driver.c.
References LIS3DH_FIFO_CTRL_REG, LIS3DH_ReadReg(), LIS3DH_TR, LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
         return MEMS_ERROR;
     value &= 0xDF;
     value |= (tr<<LIS3DH_TR);
     if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetWaterMark()
status_t LIS3DH_SetWaterMark (u8_t wtm)
Definition at line 1264 of file lis3dh_driver.c.
References LIS3DH_FIFO_CTRL_REG, LIS3DH_ReadReg(), LIS3DH_WriteReg(), MEMS_ERROR, and MEMS_SUCCESS.
{
     u8_t value;
     if(wtm > 31)
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
         return MEMS_ERROR;
     value &= 0xE0;
     value |= wtm;
     if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_WriteReg()
u8_t LIS3DH_WriteReg (u8_t WriteAddr, u8_t Data)
Definition at line 73 of file lis3dh_driver.c.
References _i2c_xfer().
Referenced by LIS3DH_FIFOModeEnable(), LIS3DH_HPFAOI1Enable(), LIS3DH_HPFAOI2Enable(), LIS3DH_HPFClickEnable(), LIS3DH_Int1LatchEnable(), LIS3DH_SetADCAux(), LIS3DH_SetAxis(), LIS3DH_SetBDU(), LIS3DH_SetBLE(), LIS3DH_SetClickCFG(), LIS3DH_SetClickLATENCY(), LIS3DH_SetClickLIMIT(), LIS3DH_SetClickTHS(), LIS3DH_SetClickWINDOW(), LIS3DH_SetFilterDataSel(), LIS3DH_SetFullScale(), LIS3DH_SetHPFCutOFF(), LIS3DH_SetHPFMode(), LIS3DH_SetInt1Duration(), LIS3DH_SetInt1Pin(), LIS3DH_SetInt1Threshold(), LIS3DH_SetInt2Pin(), LIS3DH_SetInt6D4DConfiguration(), LIS3DH_SetIntConfiguration(), LIS3DH_SetIntMode(), LIS3DH_SetMode(), LIS3DH_SetODR(), LIS3DH_SetSelfTest(), LIS3DH_SetSPIInterface(), LIS3DH_SetTemperature(), LIS3DH_SetTriggerInt(), and LIS3DH_SetWaterMark().
{
     //To be completed with either I2c or SPI writing function
     //i.e. SPI_Mems_Write_Reg(WriteAddr, Data);
     // added i2c xfer function FHTW
     _i2c_xfer (0, WriteAddr, Data, 0);
     return 1;
 }