XMC4500 Barebone Template: inc/lis3dh_driver.h File Reference
lis3dh_driver.h File Reference
lis3dh driver header
#include "3Daccel_app.h"
Data Structures
struct LIS3DH_Aux123Raw_t
Macros
#define LIS3DH_ADR 0x18
#define LIS3DH_RD_ADR (LIS3DH_ADR<<1)
#define LIS3DH_WHO_AM_I 0x0F
#define LIS3DH_CTRL_REG1 0x20
#define LIS3DH_ODR_BIT BIT(4)
#define LIS3DH_LPEN BIT(3)
#define LIS3DH_ZEN BIT(2)
#define LIS3DH_YEN BIT(1)
#define LIS3DH_XEN BIT(0)
#define LIS3DH_CTRL_REG2 0x21
#define LIS3DH_HPM BIT(6)
#define LIS3DH_HPCF BIT(4)
#define LIS3DH_FDS BIT(3)
#define LIS3DH_HPCLICK BIT(2)
#define LIS3DH_HPIS2 BIT(1)
#define LIS3DH_HPIS1 BIT(0)
#define LIS3DH_CTRL_REG3 0x22
#define LIS3DH_I1_CLICK BIT(7)
#define LIS3DH_I1_AOI1 BIT(6)
#define LIS3DH_I1_AOI2 BIT(5)
#define LIS3DH_I1_DRDY1 BIT(4)
#define LIS3DH_I1_DRDY2 BIT(3)
#define LIS3DH_I1_WTM BIT(2)
#define LIS3DH_I1_ORUN BIT(1)
#define LIS3DH_CTRL_REG6 0x25
#define LIS3DH_I2_CLICK BIT(7)
#define LIS3DH_I2_INT1 BIT(6)
#define LIS3DH_I2_BOOT BIT(4)
#define LIS3DH_H_LACTIVE BIT(1)
#define LIS3DH_TEMP_CFG_REG 0x1F
#define LIS3DH_ADC_PD BIT(7)
#define LIS3DH_TEMP_EN BIT(6)
#define LIS3DH_CTRL_REG4 0x23
#define LIS3DH_BDU BIT(7)
#define LIS3DH_BLE BIT(6)
#define LIS3DH_FS BIT(4)
#define LIS3DH_HR BIT(3)
#define LIS3DH_ST BIT(1)
#define LIS3DH_SIM BIT(0)
#define LIS3DH_CTRL_REG5 0x24
#define LIS3DH_BOOT BIT(7)
#define LIS3DH_FIFO_EN BIT(6)
#define LIS3DH_LIR_INT1 BIT(3)
#define LIS3DH_D4D_INT1 BIT(2)
#define LIS3DH_REFERENCE_REG 0x26
#define LIS3DH_REF BIT(0)
#define LIS3DH_STATUS_REG 0x27
#define LIS3DH_ZYXOR BIT(7)
#define LIS3DH_ZOR BIT(6)
#define LIS3DH_YOR BIT(5)
#define LIS3DH_XOR BIT(4)
#define LIS3DH_ZYXDA BIT(3)
#define LIS3DH_ZDA BIT(2)
#define LIS3DH_YDA BIT(1)
#define LIS3DH_XDA BIT(0)
#define LIS3DH_STATUS_AUX 0x07
#define LIS3DH_INT1_CFG 0x30
#define LIS3DH_ANDOR BIT(7)
#define LIS3DH_INT_6D BIT(6)
#define LIS3DH_ZHIE BIT(5)
#define LIS3DH_ZLIE BIT(4)
#define LIS3DH_YHIE BIT(3)
#define LIS3DH_YLIE BIT(2)
#define LIS3DH_XHIE BIT(1)
#define LIS3DH_XLIE BIT(0)
#define LIS3DH_FIFO_CTRL_REG 0x2E
#define LIS3DH_FM BIT(6)
#define LIS3DH_TR BIT(5)
#define LIS3DH_FTH BIT(0)
#define LIS3DH_CLICK_ON_PIN_INT1_ENABLE 0x80
#define LIS3DH_CLICK_ON_PIN_INT1_DISABLE 0x00
#define LIS3DH_I1_INT1_ON_PIN_INT1_ENABLE 0x40
#define LIS3DH_I1_INT1_ON_PIN_INT1_DISABLE 0x00
#define LIS3DH_I1_INT2_ON_PIN_INT1_ENABLE 0x20
#define LIS3DH_I1_INT2_ON_PIN_INT1_DISABLE 0x00
#define LIS3DH_I1_DRDY1_ON_INT1_ENABLE 0x10
#define LIS3DH_I1_DRDY1_ON_INT1_DISABLE 0x00
#define LIS3DH_I1_DRDY2_ON_INT1_ENABLE 0x08
#define LIS3DH_I1_DRDY2_ON_INT1_DISABLE 0x00
#define LIS3DH_WTM_ON_INT1_ENABLE 0x04
#define LIS3DH_WTM_ON_INT1_DISABLE 0x00
#define LIS3DH_INT1_OVERRUN_ENABLE 0x02
#define LIS3DH_INT1_OVERRUN_DISABLE 0x00
#define LIS3DH_CLICK_ON_PIN_INT2_ENABLE 0x80
#define LIS3DH_CLICK_ON_PIN_INT2_DISABLE 0x00
#define LIS3DH_I2_INT1_ON_PIN_INT2_ENABLE 0x40
#define LIS3DH_I2_INT1_ON_PIN_INT2_DISABLE 0x00
#define LIS3DH_I2_INT2_ON_PIN_INT2_ENABLE 0x20
#define LIS3DH_I2_INT2_ON_PIN_INT2_DISABLE 0x00
#define LIS3DH_I2_BOOT_ON_INT2_ENABLE 0x10
#define LIS3DH_I2_BOOT_ON_INT2_DISABLE 0x00
#define LIS3DH_INT_ACTIVE_HIGH 0x00
#define LIS3DH_INT_ACTIVE_LOW 0x02
#define LIS3DH_INT1_AND 0x80
#define LIS3DH_INT1_OR 0x00
#define LIS3DH_INT1_ZHIE_ENABLE 0x20
#define LIS3DH_INT1_ZHIE_DISABLE 0x00
#define LIS3DH_INT1_ZLIE_ENABLE 0x10
#define LIS3DH_INT1_ZLIE_DISABLE 0x00
#define LIS3DH_INT1_YHIE_ENABLE 0x08
#define LIS3DH_INT1_YHIE_DISABLE 0x00
#define LIS3DH_INT1_YLIE_ENABLE 0x04
#define LIS3DH_INT1_YLIE_DISABLE 0x00
#define LIS3DH_INT1_XHIE_ENABLE 0x02
#define LIS3DH_INT1_XHIE_DISABLE 0x00
#define LIS3DH_INT1_XLIE_ENABLE 0x01
#define LIS3DH_INT1_XLIE_DISABLE 0x00
#define LIS3DH_INT1_SRC_IA 0x40
#define LIS3DH_INT1_SRC_ZH 0x20
#define LIS3DH_INT1_SRC_ZL 0x10
#define LIS3DH_INT1_SRC_YH 0x08
#define LIS3DH_INT1_SRC_YL 0x04
#define LIS3DH_INT1_SRC_XH 0x02
#define LIS3DH_INT1_SRC_XL 0x01
#define LIS3DH_INT1_THS 0x32
#define LIS3DH_INT1_DURATION 0x33
#define LIS3DH_INT1_SRC 0x31
#define LIS3DH_FIFO_SRC_WTM 0x80
#define LIS3DH_FIFO_SRC_OVRUN 0x40
#define LIS3DH_FIFO_SRC_EMPTY 0x20
#define LIS3DH_CLICK_CFG 0x38
#define LIS3DH_ZD_ENABLE 0x20
#define LIS3DH_ZD_DISABLE 0x00
#define LIS3DH_ZS_ENABLE 0x10
#define LIS3DH_ZS_DISABLE 0x00
#define LIS3DH_YD_ENABLE 0x08
#define LIS3DH_YD_DISABLE 0x00
#define LIS3DH_YS_ENABLE 0x04
#define LIS3DH_YS_DISABLE 0x00
#define LIS3DH_XD_ENABLE 0x02
#define LIS3DH_XD_DISABLE 0x00
#define LIS3DH_XS_ENABLE 0x01
#define LIS3DH_XS_DISABLE 0x00
#define LIS3DH_CLICK_SRC 0x39
#define LIS3DH_IA 0x40
#define LIS3DH_DCLICK 0x20
#define LIS3DH_SCLICK 0x10
#define LIS3DH_CLICK_SIGN 0x08
#define LIS3DH_CLICK_Z 0x04
#define LIS3DH_CLICK_Y 0x02
#define LIS3DH_CLICK_X 0x01
#define LIS3DH_CLICK_THS 0x3A
#define LIS3DH_TIME_LIMIT 0x3B
#define LIS3DH_TIME_LATENCY 0x3C
#define LIS3DH_TIME_WINDOW 0x3D
#define LIS3DH_OUT_X_L 0x28
#define LIS3DH_OUT_X_H 0x29
#define LIS3DH_OUT_Y_L 0x2A
#define LIS3DH_OUT_Y_H 0x2B
#define LIS3DH_OUT_Z_L 0x2C
#define LIS3DH_OUT_Z_H 0x2D
#define LIS3DH_OUT_1_L 0x08
#define LIS3DH_OUT_1_H 0x09
#define LIS3DH_OUT_2_L 0x0A
#define LIS3DH_OUT_2_H 0x0B
#define LIS3DH_OUT_3_L 0x0C
#define LIS3DH_OUT_3_H 0x0D
#define LIS3DH_STATUS_REG_ZYXOR 0x80
#define LIS3DH_STATUS_REG_ZOR 0x40
#define LIS3DH_STATUS_REG_YOR 0x20
#define LIS3DH_STATUS_REG_XOR 0x10
#define LIS3DH_STATUS_REG_ZYXDA 0x08
#define LIS3DH_STATUS_REG_ZDA 0x04
#define LIS3DH_STATUS_REG_YDA 0x02
#define LIS3DH_STATUS_REG_XDA 0x01
#define LIS3DH_DATAREADY_BIT LIS3DH_STATUS_REG_ZYXDA
#define LIS3DH_STATUS_AUX_321OR 0x80
#define LIS3DH_STATUS_AUX_3OR 0x40
#define LIS3DH_STATUS_AUX_2OR 0x20
#define LIS3DH_STATUS_AUX_1OR 0x10
#define LIS3DH_STATUS_AUX_321DA 0x08
#define LIS3DH_STATUS_AUX_3DA 0x04
#define LIS3DH_STATUS_AUX_2DA 0x02
#define LIS3DH_STATUS_AUX_1DA 0x01
#define LIS3DH_MEMS_I2C_ADDRESS 0x33
#define LIS3DH_FIFO_CTRL_REG 0x2E
#define LIS3DH_FIFO_SRC_REG 0x2F
Typedefs
typedef u8_t LIS3DH_IntPinConf_t
typedef u8_t LIS3DH_Axis_t
typedef u8_t LIS3DH_Int1Conf_t
Enumerations
enum LIS3DH_ODR_t {
LIS3DH_ODR_1Hz = 0x01, LIS3DH_ODR_10Hz = 0x02, LIS3DH_ODR_25Hz = 0x03, LIS3DH_ODR_50Hz = 0x04,
LIS3DH_ODR_100Hz = 0x05, LIS3DH_ODR_200Hz = 0x06, LIS3DH_ODR_400Hz = 0x07, LIS3DH_ODR_1620Hz_LP = 0x08,
LIS3DH_ODR_1344Hz_NP_5367HZ_LP = 0x09
}
enum LIS3DH_Mode_t { LIS3DH_POWER_DOWN = 0x00, LIS3DH_LOW_POWER = 0x01, LIS3DH_NORMAL = 0x02 }
enum LIS3DH_HPFMode_t { LIS3DH_HPM_NORMAL_MODE_RES = 0x00, LIS3DH_HPM_REF_SIGNAL = 0x01, LIS3DH_HPM_NORMAL_MODE = 0x02, LIS3DH_HPM_AUTORESET_INT = 0x03 }
enum LIS3DH_HPFCutOffFreq_t { LIS3DH_HPFCF_0 = 0x00, LIS3DH_HPFCF_1 = 0x01, LIS3DH_HPFCF_2 = 0x02, LIS3DH_HPFCF_3 = 0x03 }
enum LIS3DH_Fullscale_t { LIS3DH_FULLSCALE_2 = 0x00, LIS3DH_FULLSCALE_4 = 0x01, LIS3DH_FULLSCALE_8 = 0x02, LIS3DH_FULLSCALE_16 = 0x03 }
enum LIS3DH_Endianess_t { LIS3DH_BLE_LSB = 0x00, LIS3DH_BLE_MSB = 0x01 }
enum LIS3DH_SelfTest_t { LIS3DH_SELF_TEST_DISABLE = 0x00, LIS3DH_SELF_TEST_0 = 0x01, LIS3DH_SELF_TEST_1 = 0x02 }
enum LIS3DH_FifoMode_t {
LIS3DH_FIFO_BYPASS_MODE = 0x00, LIS3DH_FIFO_MODE = 0x01, LIS3DH_FIFO_STREAM_MODE = 0x02, LIS3DH_FIFO_TRIGGER_MODE = 0x03,
LIS3DH_FIFO_DISABLE = 0x04
}
enum LIS3DH_TrigInt_t { LIS3DH_TRIG_INT1 = 0x00, LIS3DH_TRIG_INT2 = 0x01 }
enum LIS3DH_SPIMode_t { LIS3DH_SPI_4_WIRE = 0x00, LIS3DH_SPI_3_WIRE = 0x01 }
enum LIS3DH_AXISenable_t {
LIS3DH_X_ENABLE = 0x01, LIS3DH_X_DISABLE = 0x00, LIS3DH_Y_ENABLE = 0x02, LIS3DH_Y_DISABLE = 0x00,
LIS3DH_Z_ENABLE = 0x04, LIS3DH_Z_DISABLE = 0x00
}
enum LIS3DH_INT_6D_4D_t { LIS3DH_INT1_6D_4D_DISABLE = 0x00, LIS3DH_INT1_6D_ENABLE = 0x01, LIS3DH_INT1_4D_ENABLE = 0x02 }
enum LIS3DH_POSITION_6D_t {
LIS3DH_UP_SX = 0x44, LIS3DH_UP_DX = 0x42, LIS3DH_DW_SX = 0x41, LIS3DH_DW_DX = 0x48,
LIS3DH_TOP = 0x60, LIS3DH_BOTTOM = 0x50
}
enum LIS3DH_Int1Mode_t { LIS3DH_INT_MODE_OR = 0x00, LIS3DH_INT_MODE_6D_MOVEMENT = 0x01, LIS3DH_INT_MODE_AND = 0x02, LIS3DH_INT_MODE_6D_POSITION = 0x03 }
enum LIS3DH_Click_Response {
LIS3DH_DCLICK_Z_P = 0x24, LIS3DH_DCLICK_Z_N = 0x2C, LIS3DH_SCLICK_Z_P = 0x14, LIS3DH_SCLICK_Z_N = 0x1C,
LIS3DH_DCLICK_Y_P = 0x22, LIS3DH_DCLICK_Y_N = 0x2A, LIS3DH_SCLICK_Y_P = 0x12, LIS3DH_SCLICK_Y_N = 0x1A,
LIS3DH_DCLICK_X_P = 0x21, LIS3DH_DCLICK_X_N = 0x29, LIS3DH_SCLICK_X_P = 0x11, LIS3DH_SCLICK_X_N = 0x19,
LIS3DH_NO_CLICK = 0x00
}
Functions
status_t LIS3DH_SetODR (LIS3DH_ODR_t ov)
status_t LIS3DH_SetMode (LIS3DH_Mode_t md)
status_t LIS3DH_SetAxis (LIS3DH_Axis_t axis)
status_t LIS3DH_SetFullScale (LIS3DH_Fullscale_t fs)
status_t LIS3DH_SetBDU (State_t bdu)
status_t LIS3DH_SetBLE (LIS3DH_Endianess_t ble)
status_t LIS3DH_SetSelfTest (LIS3DH_SelfTest_t st)
status_t LIS3DH_SetTemperature (State_t state)
status_t LIS3DH_SetADCAux (State_t state)
status_t LIS3DH_HPFClickEnable (State_t hpfe)
status_t LIS3DH_HPFAOI1Enable (State_t hpfe)
status_t LIS3DH_HPFAOI2Enable (State_t hpfe)
status_t LIS3DH_SetHPFMode (LIS3DH_HPFMode_t hpf)
status_t LIS3DH_SetHPFCutOFF (LIS3DH_HPFCutOffFreq_t hpf)
status_t LIS3DH_SetFilterDataSel (State_t state)
status_t LIS3DH_SetInt1Pin (LIS3DH_IntPinConf_t pinConf)
status_t LIS3DH_SetInt2Pin (LIS3DH_IntPinConf_t pinConf)
status_t LIS3DH_Int1LatchEnable (State_t latch)
status_t LIS3DH_ResetInt1Latch (void)
status_t LIS3DH_SetIntConfiguration (LIS3DH_Int1Conf_t ic)
status_t LIS3DH_SetInt1Threshold (u8_t ths)
status_t LIS3DH_SetInt1Duration (LIS3DH_Int1Conf_t id)
status_t LIS3DH_SetIntMode (LIS3DH_Int1Mode_t ic)
status_t LIS3DH_SetClickCFG (u8_t status)
status_t LIS3DH_SetInt6D4DConfiguration (LIS3DH_INT_6D_4D_t ic)
status_t LIS3DH_GetInt1Src (u8_t *val)
status_t LIS3DH_GetInt1SrcBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_FIFOModeEnable (LIS3DH_FifoMode_t fm)
status_t LIS3DH_SetWaterMark (u8_t wtm)
status_t LIS3DH_SetTriggerInt (LIS3DH_TrigInt_t tr)
status_t LIS3DH_GetFifoSourceReg (u8_t *val)
status_t LIS3DH_GetFifoSourceBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_GetFifoSourceFSS (u8_t *val)
status_t LIS3DH_GetStatusReg (u8_t *val)
status_t LIS3DH_GetStatusBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_GetStatusAUXBit (u8_t statusBIT, u8_t *val)
status_t LIS3DH_GetStatusAUX (u8_t *val)
status_t LIS3DH_GetAccAxesRaw (AxesRaw_t *buff)
status_t LIS3DH_GetAuxRaw (LIS3DH_Aux123Raw_t *buff)
status_t LIS3DH_GetClickResponse (u8_t *val)
status_t LIS3DH_GetTempRaw (i8_t *val)
status_t LIS3DH_GetWHO_AM_I (u8_t *val)
status_t LIS3DH_Get6DPosition (u8_t *val)
u8_t LIS3DH_ReadReg (u8_t Reg, u8_t *Data)
u8_t LIS3DH_WriteReg (u8_t Reg, u8_t Data)
Detailed Description
lis3dh driver header
Version
x
Date
x
Author
STMicroelectronics
Definition in file lis3dh_driver.h.
Macro Definition Documentation
LIS3DH_ADC_PD
#define LIS3DH_ADC_PD BIT(7)
Definition at line 261 of file lis3dh_driver.h.
Referenced by LIS3DH_SetADCAux().
LIS3DH_ADR
#define LIS3DH_ADR 0x18
Definition at line 43 of file lis3dh_driver.h.
LIS3DH_ANDOR
#define LIS3DH_ANDOR BIT(7)
Definition at line 300 of file lis3dh_driver.h.
LIS3DH_BDU
#define LIS3DH_BDU BIT(7)
Definition at line 266 of file lis3dh_driver.h.
Referenced by LIS3DH_SetBDU().
LIS3DH_BLE
#define LIS3DH_BLE BIT(6)
Definition at line 267 of file lis3dh_driver.h.
Referenced by LIS3DH_SetBLE().
LIS3DH_BOOT
#define LIS3DH_BOOT BIT(7)
Definition at line 275 of file lis3dh_driver.h.
LIS3DH_CLICK_CFG
#define LIS3DH_CLICK_CFG 0x38
Definition at line 381 of file lis3dh_driver.h.
Referenced by LIS3DH_SetClickCFG().
LIS3DH_CLICK_ON_PIN_INT1_DISABLE
#define LIS3DH_CLICK_ON_PIN_INT1_DISABLE 0x00
Definition at line 317 of file lis3dh_driver.h.
LIS3DH_CLICK_ON_PIN_INT1_ENABLE
#define LIS3DH_CLICK_ON_PIN_INT1_ENABLE 0x80
Definition at line 316 of file lis3dh_driver.h.
LIS3DH_CLICK_ON_PIN_INT2_DISABLE
#define LIS3DH_CLICK_ON_PIN_INT2_DISABLE 0x00
Definition at line 333 of file lis3dh_driver.h.
LIS3DH_CLICK_ON_PIN_INT2_ENABLE
#define LIS3DH_CLICK_ON_PIN_INT2_ENABLE 0x80
Definition at line 332 of file lis3dh_driver.h.
LIS3DH_CLICK_SIGN
#define LIS3DH_CLICK_SIGN 0x08
Definition at line 402 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_CLICK_SRC
#define LIS3DH_CLICK_SRC 0x39
Definition at line 397 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_CLICK_THS
#define LIS3DH_CLICK_THS 0x3A
Definition at line 408 of file lis3dh_driver.h.
Referenced by LIS3DH_SetClickTHS().
LIS3DH_CLICK_X
#define LIS3DH_CLICK_X 0x01
Definition at line 405 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_CLICK_Y
#define LIS3DH_CLICK_Y 0x02
Definition at line 404 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_CLICK_Z
#define LIS3DH_CLICK_Z 0x04
Definition at line 403 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_CTRL_REG1
#define LIS3DH_CTRL_REG1 0x20
Definition at line 226 of file lis3dh_driver.h.
Referenced by LIS3DH_SetAxis(), LIS3DH_SetMode(), and LIS3DH_SetODR().
LIS3DH_CTRL_REG2
#define LIS3DH_CTRL_REG2 0x21
Definition at line 234 of file lis3dh_driver.h.
Referenced by LIS3DH_HPFAOI1Enable(), LIS3DH_HPFAOI2Enable(), LIS3DH_HPFClickEnable(), LIS3DH_SetFilterDataSel(), LIS3DH_SetHPFCutOFF(), and LIS3DH_SetHPFMode().
LIS3DH_CTRL_REG3
#define LIS3DH_CTRL_REG3 0x22
Definition at line 243 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt1Pin().
LIS3DH_CTRL_REG4
#define LIS3DH_CTRL_REG4 0x23
Definition at line 265 of file lis3dh_driver.h.
Referenced by LIS3DH_SetBDU(), LIS3DH_SetBLE(), LIS3DH_SetFullScale(), LIS3DH_SetMode(), LIS3DH_SetSelfTest(), and LIS3DH_SetSPIInterface().
LIS3DH_CTRL_REG5
#define LIS3DH_CTRL_REG5 0x24
Definition at line 274 of file lis3dh_driver.h.
Referenced by LIS3DH_FIFOModeEnable(), LIS3DH_Int1LatchEnable(), and LIS3DH_SetInt6D4DConfiguration().
LIS3DH_CTRL_REG6
#define LIS3DH_CTRL_REG6 0x25
Definition at line 253 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt2Pin().
LIS3DH_D4D_INT1
#define LIS3DH_D4D_INT1 BIT(2)
Definition at line 278 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt6D4DConfiguration().
LIS3DH_DATAREADY_BIT
#define LIS3DH_DATAREADY_BIT LIS3DH_STATUS_REG_ZYXDA
Definition at line 446 of file lis3dh_driver.h.
LIS3DH_DCLICK
#define LIS3DH_DCLICK 0x20
Definition at line 400 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_FDS
#define LIS3DH_FDS BIT(3)
Definition at line 237 of file lis3dh_driver.h.
Referenced by LIS3DH_SetFilterDataSel().
LIS3DH_FIFO_CTRL_REG [1/2]
#define LIS3DH_FIFO_CTRL_REG 0x2E
Definition at line 462 of file lis3dh_driver.h.
Referenced by LIS3DH_FIFOModeEnable(), LIS3DH_SetTriggerInt(), and LIS3DH_SetWaterMark().
LIS3DH_FIFO_CTRL_REG [2/2]
#define LIS3DH_FIFO_CTRL_REG 0x2E
Definition at line 462 of file lis3dh_driver.h.
LIS3DH_FIFO_EN
#define LIS3DH_FIFO_EN BIT(6)
Definition at line 276 of file lis3dh_driver.h.
Referenced by LIS3DH_FIFOModeEnable().
LIS3DH_FIFO_SRC_EMPTY
#define LIS3DH_FIFO_SRC_EMPTY 0x20
Definition at line 378 of file lis3dh_driver.h.
Referenced by LIS3DH_GetFifoSourceBit().
LIS3DH_FIFO_SRC_OVRUN
#define LIS3DH_FIFO_SRC_OVRUN 0x40
Definition at line 377 of file lis3dh_driver.h.
Referenced by LIS3DH_GetFifoSourceBit().
LIS3DH_FIFO_SRC_REG
#define LIS3DH_FIFO_SRC_REG 0x2F
Definition at line 463 of file lis3dh_driver.h.
Referenced by LIS3DH_GetFifoSourceBit(), LIS3DH_GetFifoSourceFSS(), and LIS3DH_GetFifoSourceReg().
LIS3DH_FIFO_SRC_WTM
#define LIS3DH_FIFO_SRC_WTM 0x80
Definition at line 376 of file lis3dh_driver.h.
Referenced by LIS3DH_GetFifoSourceBit().
LIS3DH_FM
#define LIS3DH_FM BIT(6)
Definition at line 311 of file lis3dh_driver.h.
Referenced by LIS3DH_FIFOModeEnable().
LIS3DH_FS
#define LIS3DH_FS BIT(4)
Definition at line 268 of file lis3dh_driver.h.
Referenced by LIS3DH_SetFullScale().
LIS3DH_FTH
#define LIS3DH_FTH BIT(0)
Definition at line 313 of file lis3dh_driver.h.
LIS3DH_H_LACTIVE
#define LIS3DH_H_LACTIVE BIT(1)
Definition at line 257 of file lis3dh_driver.h.
LIS3DH_HPCF
#define LIS3DH_HPCF BIT(4)
Definition at line 236 of file lis3dh_driver.h.
Referenced by LIS3DH_SetHPFCutOFF().
LIS3DH_HPCLICK
#define LIS3DH_HPCLICK BIT(2)
Definition at line 238 of file lis3dh_driver.h.
Referenced by LIS3DH_HPFClickEnable().
LIS3DH_HPIS1
#define LIS3DH_HPIS1 BIT(0)
Definition at line 240 of file lis3dh_driver.h.
Referenced by LIS3DH_HPFAOI1Enable().
LIS3DH_HPIS2
#define LIS3DH_HPIS2 BIT(1)
Definition at line 239 of file lis3dh_driver.h.
Referenced by LIS3DH_HPFAOI2Enable().
LIS3DH_HPM
#define LIS3DH_HPM BIT(6)
Definition at line 235 of file lis3dh_driver.h.
Referenced by LIS3DH_SetHPFMode().
LIS3DH_HR
#define LIS3DH_HR BIT(3)
Definition at line 269 of file lis3dh_driver.h.
Referenced by LIS3DH_SetMode().
LIS3DH_I1_AOI1
#define LIS3DH_I1_AOI1 BIT(6)
Definition at line 245 of file lis3dh_driver.h.
LIS3DH_I1_AOI2
#define LIS3DH_I1_AOI2 BIT(5)
Definition at line 246 of file lis3dh_driver.h.
LIS3DH_I1_CLICK
#define LIS3DH_I1_CLICK BIT(7)
Definition at line 244 of file lis3dh_driver.h.
LIS3DH_I1_DRDY1
#define LIS3DH_I1_DRDY1 BIT(4)
Definition at line 247 of file lis3dh_driver.h.
LIS3DH_I1_DRDY1_ON_INT1_DISABLE
#define LIS3DH_I1_DRDY1_ON_INT1_DISABLE 0x00
Definition at line 323 of file lis3dh_driver.h.
LIS3DH_I1_DRDY1_ON_INT1_ENABLE
#define LIS3DH_I1_DRDY1_ON_INT1_ENABLE 0x10
Definition at line 322 of file lis3dh_driver.h.
LIS3DH_I1_DRDY2
#define LIS3DH_I1_DRDY2 BIT(3)
Definition at line 248 of file lis3dh_driver.h.
LIS3DH_I1_DRDY2_ON_INT1_DISABLE
#define LIS3DH_I1_DRDY2_ON_INT1_DISABLE 0x00
Definition at line 325 of file lis3dh_driver.h.
LIS3DH_I1_DRDY2_ON_INT1_ENABLE
#define LIS3DH_I1_DRDY2_ON_INT1_ENABLE 0x08
Definition at line 324 of file lis3dh_driver.h.
LIS3DH_I1_INT1_ON_PIN_INT1_DISABLE
#define LIS3DH_I1_INT1_ON_PIN_INT1_DISABLE 0x00
Definition at line 319 of file lis3dh_driver.h.
LIS3DH_I1_INT1_ON_PIN_INT1_ENABLE
#define LIS3DH_I1_INT1_ON_PIN_INT1_ENABLE 0x40
Definition at line 318 of file lis3dh_driver.h.
LIS3DH_I1_INT2_ON_PIN_INT1_DISABLE
#define LIS3DH_I1_INT2_ON_PIN_INT1_DISABLE 0x00
Definition at line 321 of file lis3dh_driver.h.
LIS3DH_I1_INT2_ON_PIN_INT1_ENABLE
#define LIS3DH_I1_INT2_ON_PIN_INT1_ENABLE 0x20
Definition at line 320 of file lis3dh_driver.h.
LIS3DH_I1_ORUN
#define LIS3DH_I1_ORUN BIT(1)
Definition at line 250 of file lis3dh_driver.h.
LIS3DH_I1_WTM
#define LIS3DH_I1_WTM BIT(2)
Definition at line 249 of file lis3dh_driver.h.
LIS3DH_I2_BOOT
#define LIS3DH_I2_BOOT BIT(4)
Definition at line 256 of file lis3dh_driver.h.
LIS3DH_I2_BOOT_ON_INT2_DISABLE
#define LIS3DH_I2_BOOT_ON_INT2_DISABLE 0x00
Definition at line 339 of file lis3dh_driver.h.
LIS3DH_I2_BOOT_ON_INT2_ENABLE
#define LIS3DH_I2_BOOT_ON_INT2_ENABLE 0x10
Definition at line 338 of file lis3dh_driver.h.
LIS3DH_I2_CLICK
#define LIS3DH_I2_CLICK BIT(7)
Definition at line 254 of file lis3dh_driver.h.
LIS3DH_I2_INT1
#define LIS3DH_I2_INT1 BIT(6)
Definition at line 255 of file lis3dh_driver.h.
LIS3DH_I2_INT1_ON_PIN_INT2_DISABLE
#define LIS3DH_I2_INT1_ON_PIN_INT2_DISABLE 0x00
Definition at line 335 of file lis3dh_driver.h.
LIS3DH_I2_INT1_ON_PIN_INT2_ENABLE
#define LIS3DH_I2_INT1_ON_PIN_INT2_ENABLE 0x40
Definition at line 334 of file lis3dh_driver.h.
LIS3DH_I2_INT2_ON_PIN_INT2_DISABLE
#define LIS3DH_I2_INT2_ON_PIN_INT2_DISABLE 0x00
Definition at line 337 of file lis3dh_driver.h.
LIS3DH_I2_INT2_ON_PIN_INT2_ENABLE
#define LIS3DH_I2_INT2_ON_PIN_INT2_ENABLE 0x20
Definition at line 336 of file lis3dh_driver.h.
LIS3DH_IA
#define LIS3DH_IA 0x40
Definition at line 399 of file lis3dh_driver.h.
Referenced by LIS3DH_GetClickResponse().
LIS3DH_INT1_AND
#define LIS3DH_INT1_AND 0x80
Definition at line 344 of file lis3dh_driver.h.
LIS3DH_INT1_CFG
#define LIS3DH_INT1_CFG 0x30
Definition at line 299 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt6D4DConfiguration(), LIS3DH_SetIntConfiguration(), and LIS3DH_SetIntMode().
LIS3DH_INT1_DURATION
#define LIS3DH_INT1_DURATION 0x33
Definition at line 370 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt1Duration().
LIS3DH_INT1_OR
#define LIS3DH_INT1_OR 0x00
Definition at line 345 of file lis3dh_driver.h.
LIS3DH_INT1_OVERRUN_DISABLE
#define LIS3DH_INT1_OVERRUN_DISABLE 0x00
Definition at line 329 of file lis3dh_driver.h.
LIS3DH_INT1_OVERRUN_ENABLE
#define LIS3DH_INT1_OVERRUN_ENABLE 0x02
Definition at line 328 of file lis3dh_driver.h.
LIS3DH_INT1_SRC
#define LIS3DH_INT1_SRC 0x31
Definition at line 373 of file lis3dh_driver.h.
Referenced by LIS3DH_Get6DPosition(), LIS3DH_GetInt1Src(), LIS3DH_GetInt1SrcBit(), and LIS3DH_ResetInt1Latch().
LIS3DH_INT1_SRC_IA
#define LIS3DH_INT1_SRC_IA 0x40
Definition at line 360 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_SRC_XH
#define LIS3DH_INT1_SRC_XH 0x02
Definition at line 365 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_SRC_XL
#define LIS3DH_INT1_SRC_XL 0x01
Definition at line 366 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_SRC_YH
#define LIS3DH_INT1_SRC_YH 0x08
Definition at line 363 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_SRC_YL
#define LIS3DH_INT1_SRC_YL 0x04
Definition at line 364 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_SRC_ZH
#define LIS3DH_INT1_SRC_ZH 0x20
Definition at line 361 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_SRC_ZL
#define LIS3DH_INT1_SRC_ZL 0x10
Definition at line 362 of file lis3dh_driver.h.
Referenced by LIS3DH_GetInt1SrcBit().
LIS3DH_INT1_THS
#define LIS3DH_INT1_THS 0x32
Definition at line 369 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt1Threshold().
LIS3DH_INT1_XHIE_DISABLE
#define LIS3DH_INT1_XHIE_DISABLE 0x00
Definition at line 355 of file lis3dh_driver.h.
LIS3DH_INT1_XHIE_ENABLE
#define LIS3DH_INT1_XHIE_ENABLE 0x02
Definition at line 354 of file lis3dh_driver.h.
Referenced by configMEMSsensor().
LIS3DH_INT1_XLIE_DISABLE
#define LIS3DH_INT1_XLIE_DISABLE 0x00
Definition at line 357 of file lis3dh_driver.h.
LIS3DH_INT1_XLIE_ENABLE
#define LIS3DH_INT1_XLIE_ENABLE 0x01
Definition at line 356 of file lis3dh_driver.h.
Referenced by configMEMSsensor().
LIS3DH_INT1_YHIE_DISABLE
#define LIS3DH_INT1_YHIE_DISABLE 0x00
Definition at line 351 of file lis3dh_driver.h.
LIS3DH_INT1_YHIE_ENABLE
#define LIS3DH_INT1_YHIE_ENABLE 0x08
Definition at line 350 of file lis3dh_driver.h.
Referenced by configMEMSsensor().
LIS3DH_INT1_YLIE_DISABLE
#define LIS3DH_INT1_YLIE_DISABLE 0x00
Definition at line 353 of file lis3dh_driver.h.
LIS3DH_INT1_YLIE_ENABLE
#define LIS3DH_INT1_YLIE_ENABLE 0x04
Definition at line 352 of file lis3dh_driver.h.
Referenced by configMEMSsensor().
LIS3DH_INT1_ZHIE_DISABLE
#define LIS3DH_INT1_ZHIE_DISABLE 0x00
Definition at line 347 of file lis3dh_driver.h.
LIS3DH_INT1_ZHIE_ENABLE
#define LIS3DH_INT1_ZHIE_ENABLE 0x20
Definition at line 346 of file lis3dh_driver.h.
Referenced by configMEMSsensor().
LIS3DH_INT1_ZLIE_DISABLE
#define LIS3DH_INT1_ZLIE_DISABLE 0x00
Definition at line 349 of file lis3dh_driver.h.
LIS3DH_INT1_ZLIE_ENABLE
#define LIS3DH_INT1_ZLIE_ENABLE 0x10
Definition at line 348 of file lis3dh_driver.h.
Referenced by configMEMSsensor().
LIS3DH_INT_6D
#define LIS3DH_INT_6D BIT(6)
Definition at line 301 of file lis3dh_driver.h.
Referenced by LIS3DH_SetInt6D4DConfiguration(), and LIS3DH_SetIntMode().
LIS3DH_INT_ACTIVE_HIGH
#define LIS3DH_INT_ACTIVE_HIGH 0x00
Definition at line 340 of file lis3dh_driver.h.
LIS3DH_INT_ACTIVE_LOW
#define LIS3DH_INT_ACTIVE_LOW 0x02
Definition at line 341 of file lis3dh_driver.h.
LIS3DH_LIR_INT1
#define LIS3DH_LIR_INT1 BIT(3)
Definition at line 277 of file lis3dh_driver.h.
Referenced by LIS3DH_Int1LatchEnable().
LIS3DH_LPEN
#define LIS3DH_LPEN BIT(3)
Definition at line 228 of file lis3dh_driver.h.
Referenced by LIS3DH_SetMode().
LIS3DH_MEMS_I2C_ADDRESS
#define LIS3DH_MEMS_I2C_ADDRESS 0x33
Definition at line 459 of file lis3dh_driver.h.
LIS3DH_ODR_BIT
#define LIS3DH_ODR_BIT BIT(4)
Definition at line 227 of file lis3dh_driver.h.
Referenced by LIS3DH_SetODR().
LIS3DH_OUT_1_H
#define LIS3DH_OUT_1_H 0x09
Definition at line 423 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAuxRaw().
LIS3DH_OUT_1_L
#define LIS3DH_OUT_1_L 0x08
Definition at line 422 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAuxRaw().
LIS3DH_OUT_2_H
#define LIS3DH_OUT_2_H 0x0B
Definition at line 425 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAuxRaw().
LIS3DH_OUT_2_L
#define LIS3DH_OUT_2_L 0x0A
Definition at line 424 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAuxRaw().
LIS3DH_OUT_3_H
#define LIS3DH_OUT_3_H 0x0D
Definition at line 427 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAuxRaw(), and LIS3DH_GetTempRaw().
LIS3DH_OUT_3_L
#define LIS3DH_OUT_3_L 0x0C
Definition at line 426 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAuxRaw(), and LIS3DH_GetTempRaw().
LIS3DH_OUT_X_H
#define LIS3DH_OUT_X_H 0x29
Definition at line 415 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAccAxesRaw().
LIS3DH_OUT_X_L
#define LIS3DH_OUT_X_L 0x28
Definition at line 414 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAccAxesRaw().
LIS3DH_OUT_Y_H
#define LIS3DH_OUT_Y_H 0x2B
Definition at line 417 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAccAxesRaw().
LIS3DH_OUT_Y_L
#define LIS3DH_OUT_Y_L 0x2A
Definition at line 416 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAccAxesRaw().
LIS3DH_OUT_Z_H
#define LIS3DH_OUT_Z_H 0x2D
Definition at line 419 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAccAxesRaw().
LIS3DH_OUT_Z_L
#define LIS3DH_OUT_Z_L 0x2C
Definition at line 418 of file lis3dh_driver.h.
Referenced by LIS3DH_GetAccAxesRaw().
LIS3DH_RD_ADR
#define LIS3DH_RD_ADR (LIS3DH_ADR<<1)
Definition at line 44 of file lis3dh_driver.h.
Referenced by _i2c_xfer().
LIS3DH_REF
#define LIS3DH_REF BIT(0)
Definition at line 282 of file lis3dh_driver.h.
LIS3DH_REFERENCE_REG
#define LIS3DH_REFERENCE_REG 0x26
Definition at line 281 of file lis3dh_driver.h.
LIS3DH_SCLICK
#define LIS3DH_SCLICK 0x10
Definition at line 401 of file lis3dh_driver.h.
LIS3DH_SIM
#define LIS3DH_SIM BIT(0)
Definition at line 271 of file lis3dh_driver.h.
Referenced by LIS3DH_SetSPIInterface().
LIS3DH_ST
#define LIS3DH_ST BIT(1)
Definition at line 270 of file lis3dh_driver.h.
Referenced by LIS3DH_SetSelfTest().
LIS3DH_STATUS_AUX
#define LIS3DH_STATUS_AUX 0x07
Definition at line 296 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUX(), and LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_1DA
#define LIS3DH_STATUS_AUX_1DA 0x01
Definition at line 457 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_1OR
#define LIS3DH_STATUS_AUX_1OR 0x10
Definition at line 453 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_2DA
#define LIS3DH_STATUS_AUX_2DA 0x02
Definition at line 456 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_2OR
#define LIS3DH_STATUS_AUX_2OR 0x20
Definition at line 452 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_321DA
#define LIS3DH_STATUS_AUX_321DA 0x08
Definition at line 454 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_321OR
#define LIS3DH_STATUS_AUX_321OR 0x80
Definition at line 450 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_3DA
#define LIS3DH_STATUS_AUX_3DA 0x04
Definition at line 455 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_AUX_3OR
#define LIS3DH_STATUS_AUX_3OR 0x40
Definition at line 451 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusAUXBit().
LIS3DH_STATUS_REG
#define LIS3DH_STATUS_REG 0x27
Definition at line 285 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit(), and LIS3DH_GetStatusReg().
LIS3DH_STATUS_REG_XDA
#define LIS3DH_STATUS_REG_XDA 0x01
Definition at line 444 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_XOR
#define LIS3DH_STATUS_REG_XOR 0x10
Definition at line 436 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_YDA
#define LIS3DH_STATUS_REG_YDA 0x02
Definition at line 442 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_YOR
#define LIS3DH_STATUS_REG_YOR 0x20
Definition at line 434 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_ZDA
#define LIS3DH_STATUS_REG_ZDA 0x04
Definition at line 440 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_ZOR
#define LIS3DH_STATUS_REG_ZOR 0x40
Definition at line 432 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_ZYXDA
#define LIS3DH_STATUS_REG_ZYXDA 0x08
Definition at line 438 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_STATUS_REG_ZYXOR
#define LIS3DH_STATUS_REG_ZYXOR 0x80
Definition at line 430 of file lis3dh_driver.h.
Referenced by LIS3DH_GetStatusBit().
LIS3DH_TEMP_CFG_REG
#define LIS3DH_TEMP_CFG_REG 0x1F
Definition at line 260 of file lis3dh_driver.h.
Referenced by LIS3DH_SetADCAux(), and LIS3DH_SetTemperature().
LIS3DH_TEMP_EN
#define LIS3DH_TEMP_EN BIT(6)
Definition at line 262 of file lis3dh_driver.h.
Referenced by LIS3DH_SetTemperature().
LIS3DH_TIME_LATENCY
#define LIS3DH_TIME_LATENCY 0x3C
Definition at line 410 of file lis3dh_driver.h.
Referenced by LIS3DH_SetClickLATENCY().
LIS3DH_TIME_LIMIT
#define LIS3DH_TIME_LIMIT 0x3B
Definition at line 409 of file lis3dh_driver.h.
Referenced by LIS3DH_SetClickLIMIT().
LIS3DH_TIME_WINDOW
#define LIS3DH_TIME_WINDOW 0x3D
Definition at line 411 of file lis3dh_driver.h.
Referenced by LIS3DH_SetClickWINDOW().
LIS3DH_TR
#define LIS3DH_TR BIT(5)
Definition at line 312 of file lis3dh_driver.h.
Referenced by LIS3DH_SetTriggerInt().
LIS3DH_WHO_AM_I
#define LIS3DH_WHO_AM_I 0x0F
Definition at line 223 of file lis3dh_driver.h.
Referenced by LIS3DH_GetWHO_AM_I().
LIS3DH_WTM_ON_INT1_DISABLE
#define LIS3DH_WTM_ON_INT1_DISABLE 0x00
Definition at line 327 of file lis3dh_driver.h.
LIS3DH_WTM_ON_INT1_ENABLE
#define LIS3DH_WTM_ON_INT1_ENABLE 0x04
Definition at line 326 of file lis3dh_driver.h.
LIS3DH_XD_DISABLE
#define LIS3DH_XD_DISABLE 0x00
Definition at line 392 of file lis3dh_driver.h.
LIS3DH_XD_ENABLE
#define LIS3DH_XD_ENABLE 0x02
Definition at line 391 of file lis3dh_driver.h.
LIS3DH_XDA
#define LIS3DH_XDA BIT(0)
Definition at line 293 of file lis3dh_driver.h.
LIS3DH_XEN
#define LIS3DH_XEN BIT(0)
Definition at line 231 of file lis3dh_driver.h.
LIS3DH_XHIE
#define LIS3DH_XHIE BIT(1)
Definition at line 306 of file lis3dh_driver.h.
LIS3DH_XLIE
#define LIS3DH_XLIE BIT(0)
Definition at line 307 of file lis3dh_driver.h.
LIS3DH_XOR
#define LIS3DH_XOR BIT(4)
Definition at line 289 of file lis3dh_driver.h.
LIS3DH_XS_DISABLE
#define LIS3DH_XS_DISABLE 0x00
Definition at line 394 of file lis3dh_driver.h.
LIS3DH_XS_ENABLE
#define LIS3DH_XS_ENABLE 0x01
Definition at line 393 of file lis3dh_driver.h.
LIS3DH_YD_DISABLE
#define LIS3DH_YD_DISABLE 0x00
Definition at line 388 of file lis3dh_driver.h.
LIS3DH_YD_ENABLE
#define LIS3DH_YD_ENABLE 0x08
Definition at line 387 of file lis3dh_driver.h.
LIS3DH_YDA
#define LIS3DH_YDA BIT(1)
Definition at line 292 of file lis3dh_driver.h.
LIS3DH_YEN
#define LIS3DH_YEN BIT(1)
Definition at line 230 of file lis3dh_driver.h.
LIS3DH_YHIE
#define LIS3DH_YHIE BIT(3)
Definition at line 304 of file lis3dh_driver.h.
LIS3DH_YLIE
#define LIS3DH_YLIE BIT(2)
Definition at line 305 of file lis3dh_driver.h.
LIS3DH_YOR
#define LIS3DH_YOR BIT(5)
Definition at line 288 of file lis3dh_driver.h.
LIS3DH_YS_DISABLE
#define LIS3DH_YS_DISABLE 0x00
Definition at line 390 of file lis3dh_driver.h.
LIS3DH_YS_ENABLE
#define LIS3DH_YS_ENABLE 0x04
Definition at line 389 of file lis3dh_driver.h.
LIS3DH_ZD_DISABLE
#define LIS3DH_ZD_DISABLE 0x00
Definition at line 384 of file lis3dh_driver.h.
LIS3DH_ZD_ENABLE
#define LIS3DH_ZD_ENABLE 0x20
Definition at line 383 of file lis3dh_driver.h.
LIS3DH_ZDA
#define LIS3DH_ZDA BIT(2)
Definition at line 291 of file lis3dh_driver.h.
LIS3DH_ZEN
#define LIS3DH_ZEN BIT(2)
Definition at line 229 of file lis3dh_driver.h.
LIS3DH_ZHIE
#define LIS3DH_ZHIE BIT(5)
Definition at line 302 of file lis3dh_driver.h.
LIS3DH_ZLIE
#define LIS3DH_ZLIE BIT(4)
Definition at line 303 of file lis3dh_driver.h.
LIS3DH_ZOR
#define LIS3DH_ZOR BIT(6)
Definition at line 287 of file lis3dh_driver.h.
LIS3DH_ZS_DISABLE
#define LIS3DH_ZS_DISABLE 0x00
Definition at line 386 of file lis3dh_driver.h.
LIS3DH_ZS_ENABLE
#define LIS3DH_ZS_ENABLE 0x10
Definition at line 385 of file lis3dh_driver.h.
LIS3DH_ZYXDA
#define LIS3DH_ZYXDA BIT(3)
Definition at line 290 of file lis3dh_driver.h.
LIS3DH_ZYXOR
#define LIS3DH_ZYXOR BIT(7)
Definition at line 286 of file lis3dh_driver.h.
Typedef Documentation
LIS3DH_Axis_t
typedef u8_t LIS3DH_Axis_t
Definition at line 61 of file lis3dh_driver.h.
LIS3DH_Int1Conf_t
typedef u8_t LIS3DH_Int1Conf_t
Definition at line 62 of file lis3dh_driver.h.
LIS3DH_IntPinConf_t
typedef u8_t LIS3DH_IntPinConf_t
Definition at line 60 of file lis3dh_driver.h.
Enumeration Type Documentation
LIS3DH_AXISenable_t
enum LIS3DH_AXISenable_t
Enumerator
LIS3DH_X_ENABLE
LIS3DH_X_DISABLE
LIS3DH_Y_ENABLE
LIS3DH_Y_DISABLE
LIS3DH_Z_ENABLE
LIS3DH_Z_DISABLE
Definition at line 160 of file lis3dh_driver.h.
              {
   LIS3DH_X_ENABLE = 0x01,
   LIS3DH_X_DISABLE = 0x00,
   LIS3DH_Y_ENABLE = 0x02,
   LIS3DH_Y_DISABLE = 0x00,
   LIS3DH_Z_ENABLE = 0x04,
   LIS3DH_Z_DISABLE = 0x00
 } LIS3DH_AXISenable_t;
LIS3DH_Click_Response
enum LIS3DH_Click_Response
Enumerator
LIS3DH_DCLICK_Z_P
LIS3DH_DCLICK_Z_N
LIS3DH_SCLICK_Z_P
LIS3DH_SCLICK_Z_N
LIS3DH_DCLICK_Y_P
LIS3DH_DCLICK_Y_N
LIS3DH_SCLICK_Y_P
LIS3DH_SCLICK_Y_N
LIS3DH_DCLICK_X_P
LIS3DH_DCLICK_X_N
LIS3DH_SCLICK_X_P
LIS3DH_SCLICK_X_N
LIS3DH_NO_CLICK
Definition at line 194 of file lis3dh_driver.h.
              {
 LIS3DH_DCLICK_Z_P = 0x24,
 LIS3DH_DCLICK_Z_N = 0x2C,
 LIS3DH_SCLICK_Z_P = 0x14,
 LIS3DH_SCLICK_Z_N = 0x1C,
 LIS3DH_DCLICK_Y_P = 0x22,
 LIS3DH_DCLICK_Y_N = 0x2A,
 LIS3DH_SCLICK_Y_P = 0x12,
 LIS3DH_SCLICK_Y_N = 0x1A,
 LIS3DH_DCLICK_X_P = 0x21,
 LIS3DH_DCLICK_X_N = 0x29,
 LIS3DH_SCLICK_X_P = 0x11,
 LIS3DH_SCLICK_X_N = 0x19,
 LIS3DH_NO_CLICK = 0x00
 } LIS3DH_Click_Response;
LIS3DH_Endianess_t
enum LIS3DH_Endianess_t
Enumerator
LIS3DH_BLE_LSB
LIS3DH_BLE_MSB
Definition at line 131 of file lis3dh_driver.h.
              {
   LIS3DH_BLE_LSB = 0x00,
   LIS3DH_BLE_MSB = 0x01
 } LIS3DH_Endianess_t;
LIS3DH_FifoMode_t
enum LIS3DH_FifoMode_t
Enumerator
LIS3DH_FIFO_BYPASS_MODE
LIS3DH_FIFO_MODE
LIS3DH_FIFO_STREAM_MODE
LIS3DH_FIFO_TRIGGER_MODE
LIS3DH_FIFO_DISABLE
Definition at line 142 of file lis3dh_driver.h.
              {
   LIS3DH_FIFO_BYPASS_MODE = 0x00,
   LIS3DH_FIFO_MODE = 0x01,
   LIS3DH_FIFO_STREAM_MODE = 0x02,
   LIS3DH_FIFO_TRIGGER_MODE = 0x03,
   LIS3DH_FIFO_DISABLE = 0x04
 } LIS3DH_FifoMode_t;
LIS3DH_Fullscale_t
enum LIS3DH_Fullscale_t
Enumerator
LIS3DH_FULLSCALE_2
LIS3DH_FULLSCALE_4
LIS3DH_FULLSCALE_8
LIS3DH_FULLSCALE_16
Definition at line 124 of file lis3dh_driver.h.
              {
   LIS3DH_FULLSCALE_2 = 0x00,
   LIS3DH_FULLSCALE_4 = 0x01,
   LIS3DH_FULLSCALE_8 = 0x02,
   LIS3DH_FULLSCALE_16 = 0x03
 } LIS3DH_Fullscale_t;
LIS3DH_HPFCutOffFreq_t
enum LIS3DH_HPFCutOffFreq_t
Enumerator
LIS3DH_HPFCF_0
LIS3DH_HPFCF_1
LIS3DH_HPFCF_2
LIS3DH_HPFCF_3
Definition at line 111 of file lis3dh_driver.h.
              {
   LIS3DH_HPFCF_0 = 0x00,
   LIS3DH_HPFCF_1 = 0x01,
   LIS3DH_HPFCF_2 = 0x02,
   LIS3DH_HPFCF_3 = 0x03
 } LIS3DH_HPFCutOffFreq_t;
LIS3DH_HPFMode_t
enum LIS3DH_HPFMode_t
Enumerator
LIS3DH_HPM_NORMAL_MODE_RES
LIS3DH_HPM_REF_SIGNAL
LIS3DH_HPM_NORMAL_MODE
LIS3DH_HPM_AUTORESET_INT
Definition at line 104 of file lis3dh_driver.h.
              {
   LIS3DH_HPM_NORMAL_MODE_RES = 0x00,
   LIS3DH_HPM_REF_SIGNAL = 0x01,
   LIS3DH_HPM_NORMAL_MODE = 0x02,
   LIS3DH_HPM_AUTORESET_INT = 0x03
 } LIS3DH_HPFMode_t;
LIS3DH_Int1Mode_t
enum LIS3DH_Int1Mode_t
Enumerator
LIS3DH_INT_MODE_OR
LIS3DH_INT_MODE_6D_MOVEMENT
LIS3DH_INT_MODE_AND
LIS3DH_INT_MODE_6D_POSITION
Definition at line 184 of file lis3dh_driver.h.
              {
   LIS3DH_INT_MODE_OR = 0x00,
   LIS3DH_INT_MODE_6D_MOVEMENT = 0x01,
   LIS3DH_INT_MODE_AND = 0x02,
   LIS3DH_INT_MODE_6D_POSITION = 0x03
 } LIS3DH_Int1Mode_t;
LIS3DH_INT_6D_4D_t
enum LIS3DH_INT_6D_4D_t
Enumerator
LIS3DH_INT1_6D_4D_DISABLE
LIS3DH_INT1_6D_ENABLE
LIS3DH_INT1_4D_ENABLE
Definition at line 169 of file lis3dh_driver.h.
              {
   LIS3DH_INT1_6D_4D_DISABLE = 0x00,
   LIS3DH_INT1_6D_ENABLE = 0x01,
   LIS3DH_INT1_4D_ENABLE = 0x02
 } LIS3DH_INT_6D_4D_t;
LIS3DH_Mode_t
enum LIS3DH_Mode_t
Enumerator
LIS3DH_POWER_DOWN
LIS3DH_LOW_POWER
LIS3DH_NORMAL
Definition at line 98 of file lis3dh_driver.h.
              {
   LIS3DH_POWER_DOWN = 0x00,
   LIS3DH_LOW_POWER = 0x01,
   LIS3DH_NORMAL = 0x02
 } LIS3DH_Mode_t;
LIS3DH_ODR_t
enum LIS3DH_ODR_t
Enumerator
LIS3DH_ODR_1Hz
LIS3DH_ODR_10Hz
LIS3DH_ODR_25Hz
LIS3DH_ODR_50Hz
LIS3DH_ODR_100Hz
LIS3DH_ODR_200Hz
LIS3DH_ODR_400Hz
LIS3DH_ODR_1620Hz_LP
LIS3DH_ODR_1344Hz_NP_5367HZ_LP
Definition at line 86 of file lis3dh_driver.h.
              {
   LIS3DH_ODR_1Hz = 0x01,
   LIS3DH_ODR_10Hz = 0x02,
   LIS3DH_ODR_25Hz = 0x03,
   LIS3DH_ODR_50Hz = 0x04,
   LIS3DH_ODR_100Hz = 0x05,
   LIS3DH_ODR_200Hz = 0x06,
   LIS3DH_ODR_400Hz = 0x07,
   LIS3DH_ODR_1620Hz_LP = 0x08,
   LIS3DH_ODR_1344Hz_NP_5367HZ_LP = 0x09
 } LIS3DH_ODR_t;
LIS3DH_POSITION_6D_t
enum LIS3DH_POSITION_6D_t
Enumerator
LIS3DH_UP_SX
LIS3DH_UP_DX
LIS3DH_DW_SX
LIS3DH_DW_DX
LIS3DH_TOP
LIS3DH_BOTTOM
Definition at line 175 of file lis3dh_driver.h.
              {
   LIS3DH_UP_SX = 0x44,
   LIS3DH_UP_DX = 0x42,
   LIS3DH_DW_SX = 0x41,
   LIS3DH_DW_DX = 0x48,
   LIS3DH_TOP = 0x60,
   LIS3DH_BOTTOM = 0x50
 } LIS3DH_POSITION_6D_t;
LIS3DH_SelfTest_t
enum LIS3DH_SelfTest_t
Enumerator
LIS3DH_SELF_TEST_DISABLE
LIS3DH_SELF_TEST_0
LIS3DH_SELF_TEST_1
Definition at line 136 of file lis3dh_driver.h.
              {
   LIS3DH_SELF_TEST_DISABLE = 0x00,
   LIS3DH_SELF_TEST_0 = 0x01,
   LIS3DH_SELF_TEST_1 = 0x02
 } LIS3DH_SelfTest_t;
LIS3DH_SPIMode_t
enum LIS3DH_SPIMode_t
Enumerator
LIS3DH_SPI_4_WIRE
LIS3DH_SPI_3_WIRE
Definition at line 155 of file lis3dh_driver.h.
              {
   LIS3DH_SPI_4_WIRE = 0x00,
   LIS3DH_SPI_3_WIRE = 0x01
 } LIS3DH_SPIMode_t;
LIS3DH_TrigInt_t
enum LIS3DH_TrigInt_t
Enumerator
LIS3DH_TRIG_INT1
LIS3DH_TRIG_INT2
Definition at line 150 of file lis3dh_driver.h.
              {
   LIS3DH_TRIG_INT1 = 0x00,
   LIS3DH_TRIG_INT2 = 0x01
 } LIS3DH_TrigInt_t;
Function Documentation
LIS3DH_FIFOModeEnable()
status_t LIS3DH_FIFOModeEnable (LIS3DH_FifoMode_t fm)
Definition at line 1129 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG5, LIS3DH_FIFO_BYPASS_MODE, LIS3DH_FIFO_CTRL_REG, LIS3DH_FIFO_DISABLE, LIS3DH_FIFO_EN, LIS3DH_FIFO_MODE, LIS3DH_FIFO_STREAM_MODE, LIS3DH_FIFO_TRIGGER_MODE, LIS3DH_FM, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if(fm == LIS3DH_FIFO_DISABLE) {
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1F;
         value |= (LIS3DH_FIFO_BYPASS_MODE<<LIS3DH_FM);
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )           //fifo mode bypass
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo disable
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_BYPASS_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                     //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                      //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_STREAM_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                      //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     if(fm == LIS3DH_FIFO_TRIGGER_MODE)   {
         if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
             return MEMS_ERROR;
         value &= 0xBF;
         value |= MEMS_SET<<LIS3DH_FIFO_EN;
         if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )               //fifo enable
             return MEMS_ERROR;
         if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
             return MEMS_ERROR;
         value &= 0x1f;
         value |= (fm<<LIS3DH_FM);                      //fifo mode configuration
         if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
             return MEMS_ERROR;
     }
     return MEMS_SUCCESS;
 }
LIS3DH_Get6DPosition()
status_t LIS3DH_Get6DPosition (u8_t * val)
Definition at line 1051 of file lis3dh_driver.c.
References LIS3DH_BOTTOM, LIS3DH_DW_DX, LIS3DH_DW_SX, LIS3DH_INT1_SRC, LIS3DH_ReadReg(), LIS3DH_TOP, LIS3DH_UP_DX, and LIS3DH_UP_SX.
Referenced by get6Dposition().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     switch (value) {
     case LIS3DH_UP_SX:
         *val = LIS3DH_UP_SX;
         break;
     case LIS3DH_UP_DX:
         *val = LIS3DH_UP_DX;
         break;
     case LIS3DH_DW_SX:
         *val = LIS3DH_DW_SX;
         break;
     case LIS3DH_DW_DX:
         *val = LIS3DH_DW_DX;
         break;
     case LIS3DH_TOP:
         *val = LIS3DH_TOP;
         break;
     case LIS3DH_BOTTOM:
         *val = LIS3DH_BOTTOM;
         break;
     }
     return MEMS_SUCCESS;
 }
LIS3DH_GetAccAxesRaw()
status_t LIS3DH_GetAccAxesRaw (AxesRaw_t * buff)
Definition at line 1396 of file lis3dh_driver.c.
References LIS3DH_OUT_X_H, LIS3DH_OUT_X_L, LIS3DH_OUT_Y_H, LIS3DH_OUT_Y_L, LIS3DH_OUT_Z_H, LIS3DH_OUT_Z_L, and LIS3DH_ReadReg().
Referenced by getAxesRawData().
{
     i16_t value;
     u8_t *valueL = (u8_t *)(&value);
     u8_t *valueH = ((u8_t *)(&value)+1);
     if( !LIS3DH_ReadReg(LIS3DH_OUT_X_L, valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_X_H, valueH) )
         return MEMS_ERROR;
     buff->AXIS_X = value;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Y_L, valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Y_H, valueH) )
         return MEMS_ERROR;
     buff->AXIS_Y = value;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Z_L, valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_Z_H, valueH) )
         return MEMS_ERROR;
     buff->AXIS_Z = value;
     return MEMS_SUCCESS;
 }
LIS3DH_GetAuxRaw()
status_t LIS3DH_GetAuxRaw (LIS3DH_Aux123Raw_t * buff)
Definition at line 300 of file lis3dh_driver.c.
References LIS3DH_Aux123Raw_t::AUX_1, LIS3DH_Aux123Raw_t::AUX_2, LIS3DH_Aux123Raw_t::AUX_3, LIS3DH_OUT_1_H, LIS3DH_OUT_1_L, LIS3DH_OUT_2_H, LIS3DH_OUT_2_L, LIS3DH_OUT_3_H, LIS3DH_OUT_3_L, and LIS3DH_ReadReg().
{
     u8_t valueL;
     u8_t valueH;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_1_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_1_H, &valueH) )
         return MEMS_ERROR;
     buff->AUX_1 = (u16_t)( (valueH << 8) | valueL )/16;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_2_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_2_H, &valueH) )
         return MEMS_ERROR;
     buff->AUX_2 = (u16_t)( (valueH << 8) | valueL )/16;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_H, &valueH) )
         return MEMS_ERROR;
     buff->AUX_3 = (u16_t)( (valueH << 8) | valueL )/16;
     return MEMS_SUCCESS;
 }
LIS3DH_GetClickResponse()
status_t LIS3DH_GetClickResponse (u8_t * val)
Definition at line 832 of file lis3dh_driver.c.
References LIS3DH_CLICK_SIGN, LIS3DH_CLICK_SRC, LIS3DH_CLICK_X, LIS3DH_CLICK_Y, LIS3DH_CLICK_Z, LIS3DH_DCLICK, LIS3DH_DCLICK_X_N, LIS3DH_DCLICK_X_P, LIS3DH_DCLICK_Y_N, LIS3DH_DCLICK_Y_P, LIS3DH_DCLICK_Z_N, LIS3DH_DCLICK_Z_P, LIS3DH_IA, LIS3DH_NO_CLICK, LIS3DH_ReadReg(), LIS3DH_SCLICK_X_N, LIS3DH_SCLICK_X_P, LIS3DH_SCLICK_Y_N, LIS3DH_SCLICK_Y_P, LIS3DH_SCLICK_Z_N, and LIS3DH_SCLICK_Z_P.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CLICK_SRC, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     if((value & LIS3DH_IA)==0) {
         *res = LIS3DH_NO_CLICK;
         return MEMS_SUCCESS;
     }
     else {
         if (value & LIS3DH_DCLICK) {
             if (value & LIS3DH_CLICK_SIGN) {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_DCLICK_Z_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_DCLICK_Y_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_DCLICK_X_N;
                     return MEMS_SUCCESS;
                 }
             }
             else {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_DCLICK_Z_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_DCLICK_Y_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_DCLICK_X_P;
                     return MEMS_SUCCESS;
                 }
             }
         }
         else {
             if (value & LIS3DH_CLICK_SIGN) {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_SCLICK_Z_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_SCLICK_Y_N;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_SCLICK_X_N;
                     return MEMS_SUCCESS;
                 }
             }
             else {
                 if (value & LIS3DH_CLICK_Z) {
                     *res = LIS3DH_SCLICK_Z_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_Y) {
                     *res = LIS3DH_SCLICK_Y_P;
                     return MEMS_SUCCESS;
                 }
                 if (value & LIS3DH_CLICK_X) {
                     *res = LIS3DH_SCLICK_X_P;
                     return MEMS_SUCCESS;
                 }
             }
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetFifoSourceBit()
status_t LIS3DH_GetFifoSourceBit (u8_t statusBIT, u8_t * val)
Definition at line 1562 of file lis3dh_driver.c.
References LIS3DH_FIFO_SRC_EMPTY, LIS3DH_FIFO_SRC_OVRUN, LIS3DH_FIFO_SRC_REG, LIS3DH_FIFO_SRC_WTM, and LIS3DH_ReadReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_SRC_REG, &value) )
         return MEMS_ERROR;
     if(statusBIT == LIS3DH_FIFO_SRC_WTM) {
         if(value &= LIS3DH_FIFO_SRC_WTM) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_FIFO_SRC_OVRUN) {
         if(value &= LIS3DH_FIFO_SRC_OVRUN) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_FIFO_SRC_EMPTY) {
         if(value &= statusBIT == LIS3DH_FIFO_SRC_EMPTY) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetFifoSourceFSS()
status_t LIS3DH_GetFifoSourceFSS (u8_t * val)
Definition at line 1611 of file lis3dh_driver.c.
References LIS3DH_FIFO_SRC_REG, and LIS3DH_ReadReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_SRC_REG, &value) )
         return MEMS_ERROR;
     value &= 0x1F;
     *val = value;
     return MEMS_SUCCESS;
 }
LIS3DH_GetFifoSourceReg()
status_t LIS3DH_GetFifoSourceReg (u8_t * val)
Definition at line 1545 of file lis3dh_driver.c.
References LIS3DH_FIFO_SRC_REG, and LIS3DH_ReadReg().
{
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_SRC_REG, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetInt1Src()
status_t LIS3DH_GetInt1Src (u8_t * val)
Definition at line 1436 of file lis3dh_driver.c.
References LIS3DH_INT1_SRC, and LIS3DH_ReadReg().
{
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetInt1SrcBit()
status_t LIS3DH_GetInt1SrcBit (u8_t statusBIT, u8_t * val)
Definition at line 1453 of file lis3dh_driver.c.
References LIS3DH_INT1_SRC, LIS3DH_INT1_SRC_IA, LIS3DH_INT1_SRC_XH, LIS3DH_INT1_SRC_XL, LIS3DH_INT1_SRC_YH, LIS3DH_INT1_SRC_YL, LIS3DH_INT1_SRC_ZH, LIS3DH_INT1_SRC_ZL, and LIS3DH_ReadReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, &value) )
         return MEMS_ERROR;
     if(statusBIT == LIS3DH_INT1_SRC_IA) {
         if(value &= LIS3DH_INT1_SRC_IA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_ZH) {
         if(value &= LIS3DH_INT1_SRC_ZH) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_ZL) {
         if(value &= LIS3DH_INT1_SRC_ZL) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_YH) {
         if(value &= LIS3DH_INT1_SRC_YH) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_YL) {
         if(value &= LIS3DH_INT1_SRC_YL) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_XH) {
         if(value &= LIS3DH_INT1_SRC_XH) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_INT1_SRC_XL) {
         if(value &= LIS3DH_INT1_SRC_XL) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetStatusAUX()
status_t LIS3DH_GetStatusAUX (u8_t * val)
Definition at line 107 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), and LIS3DH_STATUS_AUX.
{
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_AUX, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetStatusAUXBit()
status_t LIS3DH_GetStatusAUXBit (u8_t statusBIT, u8_t * val)
Definition at line 125 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_STATUS_AUX, LIS3DH_STATUS_AUX_1DA, LIS3DH_STATUS_AUX_1OR, LIS3DH_STATUS_AUX_2DA, LIS3DH_STATUS_AUX_2OR, LIS3DH_STATUS_AUX_321DA, LIS3DH_STATUS_AUX_321OR, LIS3DH_STATUS_AUX_3DA, and LIS3DH_STATUS_AUX_3OR.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_AUX, &value) )
         return MEMS_ERROR;
     if(statusBIT == LIS3DH_STATUS_AUX_321OR) {
         if(value &= LIS3DH_STATUS_AUX_321OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_3OR) {
         if(value &= LIS3DH_STATUS_AUX_3OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_2OR) {
         if(value &= LIS3DH_STATUS_AUX_2OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_1OR) {
         if(value &= LIS3DH_STATUS_AUX_1OR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_321DA) {
         if(value &= LIS3DH_STATUS_AUX_321DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_3DA) {
         if(value &= LIS3DH_STATUS_AUX_3DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_2DA) {
         if(value &= LIS3DH_STATUS_AUX_2DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     if(statusBIT == LIS3DH_STATUS_AUX_1DA) {
         if(value &= LIS3DH_STATUS_AUX_1DA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetStatusBit()
status_t LIS3DH_GetStatusBit (u8_t statusBIT, u8_t * val)
Definition at line 1304 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_STATUS_REG, LIS3DH_STATUS_REG_XDA, LIS3DH_STATUS_REG_XOR, LIS3DH_STATUS_REG_YDA, LIS3DH_STATUS_REG_YOR, LIS3DH_STATUS_REG_ZDA, LIS3DH_STATUS_REG_ZOR, LIS3DH_STATUS_REG_ZYXDA, and LIS3DH_STATUS_REG_ZYXOR.
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_REG, &value) )
         return MEMS_ERROR;
     switch (statusBIT) {
     case LIS3DH_STATUS_REG_ZYXOR:
         if(value &= LIS3DH_STATUS_REG_ZYXOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_ZOR:
         if(value &= LIS3DH_STATUS_REG_ZOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_YOR:
         if(value &= LIS3DH_STATUS_REG_YOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_XOR:
         if(value &= LIS3DH_STATUS_REG_XOR) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_ZYXDA:
         if(value &= LIS3DH_STATUS_REG_ZYXDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_ZDA:
         if(value &= LIS3DH_STATUS_REG_ZDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_YDA:
         if(value &= LIS3DH_STATUS_REG_YDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     case LIS3DH_STATUS_REG_XDA:
         if(value &= LIS3DH_STATUS_REG_XDA) {
             *val = MEMS_SET;
             return MEMS_SUCCESS;
         }
         else {
             *val = MEMS_RESET;
             return MEMS_SUCCESS;
         }
     }
     return MEMS_ERROR;
 }
LIS3DH_GetStatusReg()
status_t LIS3DH_GetStatusReg (u8_t * val)
Definition at line 1286 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), and LIS3DH_STATUS_REG.
{
     if( !LIS3DH_ReadReg(LIS3DH_STATUS_REG, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_GetTempRaw()
status_t LIS3DH_GetTempRaw (i8_t * val)
Definition at line 339 of file lis3dh_driver.c.
References LIS3DH_OUT_3_H, LIS3DH_OUT_3_L, and LIS3DH_ReadReg().
Referenced by getTemperature().
{
     u8_t valueL;
     u8_t valueH;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_L, &valueL) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_OUT_3_H, &valueH) )
         return MEMS_ERROR;
     *buff = (i8_t)( valueH );
     return MEMS_SUCCESS;
 }
LIS3DH_GetWHO_AM_I()
status_t LIS3DH_GetWHO_AM_I (u8_t * val)
Definition at line 91 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), and LIS3DH_WHO_AM_I.
{
     if( !LIS3DH_ReadReg(LIS3DH_WHO_AM_I, val) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_HPFAOI1Enable()
status_t LIS3DH_HPFAOI1Enable (State_t hpfe)
Definition at line 555 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPIS1, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xFE;
     value |= (hpfe<<LIS3DH_HPIS1);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_HPFAOI2Enable()
status_t LIS3DH_HPFAOI2Enable (State_t hpfe)
Definition at line 578 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPIS2, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xFD;
     value |= (hpfe<<LIS3DH_HPIS2);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_HPFClickEnable()
status_t LIS3DH_HPFClickEnable (State_t hpfe)
Definition at line 532 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPCLICK, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xFB;
     value |= (hpfe<<LIS3DH_HPCLICK);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_Int1LatchEnable()
status_t LIS3DH_Int1LatchEnable (State_t latch)
Definition at line 917 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG5, LIS3DH_LIR_INT1, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value) )
         return MEMS_ERROR;
     value &= 0xF7;
     value |= latch<<LIS3DH_LIR_INT1;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_ReadReg()
u8_t LIS3DH_ReadReg (u8_t Reg, u8_t * Data)
Definition at line 52 of file lis3dh_driver.c.
References _i2c_xfer().
Referenced by LIS3DH_FIFOModeEnable(), LIS3DH_Get6DPosition(), LIS3DH_GetAccAxesRaw(), LIS3DH_GetAuxRaw(), LIS3DH_GetClickResponse(), LIS3DH_GetFifoSourceBit(), LIS3DH_GetFifoSourceFSS(), LIS3DH_GetFifoSourceReg(), LIS3DH_GetInt1Src(), LIS3DH_GetInt1SrcBit(), LIS3DH_GetStatusAUX(), LIS3DH_GetStatusAUXBit(), LIS3DH_GetStatusBit(), LIS3DH_GetStatusReg(), LIS3DH_GetTempRaw(), LIS3DH_GetWHO_AM_I(), LIS3DH_HPFAOI1Enable(), LIS3DH_HPFAOI2Enable(), LIS3DH_HPFClickEnable(), LIS3DH_Int1LatchEnable(), LIS3DH_ResetInt1Latch(), LIS3DH_SetADCAux(), LIS3DH_SetAxis(), LIS3DH_SetBDU(), LIS3DH_SetBLE(), LIS3DH_SetClickCFG(), LIS3DH_SetFilterDataSel(), LIS3DH_SetFullScale(), LIS3DH_SetHPFCutOFF(), LIS3DH_SetHPFMode(), LIS3DH_SetInt1Pin(), LIS3DH_SetInt2Pin(), LIS3DH_SetInt6D4DConfiguration(), LIS3DH_SetIntConfiguration(), LIS3DH_SetIntMode(), LIS3DH_SetMode(), LIS3DH_SetODR(), LIS3DH_SetSelfTest(), LIS3DH_SetSPIInterface(), LIS3DH_SetTemperature(), LIS3DH_SetTriggerInt(), and LIS3DH_SetWaterMark().
{
     //To be completed with either I2c or SPI reading function
     //i.e. *Data = SPI_Mems_Read_Reg( Reg );
     *Data = _i2c_xfer (0, Reg, 0, 1);
     return 1;
 }
LIS3DH_ResetInt1Latch()
status_t LIS3DH_ResetInt1Latch (void)
Definition at line 940 of file lis3dh_driver.c.
References LIS3DH_INT1_SRC, and LIS3DH_ReadReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_SRC, &value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetADCAux()
status_t LIS3DH_SetADCAux (State_t state)
Definition at line 277 of file lis3dh_driver.c.
References LIS3DH_ADC_PD, LIS3DH_ReadReg(), LIS3DH_TEMP_CFG_REG, and LIS3DH_WriteReg().
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_TEMP_CFG_REG, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     value |= state<<LIS3DH_ADC_PD;
     if( !LIS3DH_WriteReg(LIS3DH_TEMP_CFG_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetAxis()
status_t LIS3DH_SetAxis (LIS3DH_Axis_t axis)
Definition at line 419 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG1, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by initMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG1, &value) )
         return MEMS_ERROR;
     value &= 0xF8;
     value |= (0x07 & axis);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG1, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetBDU()
status_t LIS3DH_SetBDU (State_t bdu)
Definition at line 464 of file lis3dh_driver.c.
References LIS3DH_BDU, LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0x7F;
     value |= (bdu<<LIS3DH_BDU);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetBLE()
status_t LIS3DH_SetBLE (LIS3DH_Endianess_t ble)
Definition at line 487 of file lis3dh_driver.c.
References LIS3DH_BLE, LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xBF;
     value |= (ble<<LIS3DH_BLE);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetClickCFG()
status_t LIS3DH_SetClickCFG (u8_t status)
Definition at line 739 of file lis3dh_driver.c.
References LIS3DH_CLICK_CFG, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CLICK_CFG, &value) )
         return MEMS_ERROR;
     value &= 0xC0;
     value |= status;
     if( !LIS3DH_WriteReg(LIS3DH_CLICK_CFG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetFilterDataSel()
status_t LIS3DH_SetFilterDataSel (State_t state)
Definition at line 652 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_FDS, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xF7;
     value |= (state<<LIS3DH_FDS);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetFullScale()
status_t LIS3DH_SetFullScale (LIS3DH_Fullscale_t fs)
Definition at line 441 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG4, LIS3DH_FS, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by initMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xCF;
     value |= (fs<<LIS3DH_FS);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetHPFCutOFF()
status_t LIS3DH_SetHPFCutOFF (LIS3DH_HPFCutOffFreq_t hpf)
Definition at line 625 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPCF, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if (hpf > 3)
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0xCF;
     value |= (hpf<<LIS3DH_HPCF);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetHPFMode()
status_t LIS3DH_SetHPFMode (LIS3DH_HPFMode_t hpf)
Definition at line 602 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG2, LIS3DH_HPM, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG2, &value) )
         return MEMS_ERROR;
     value &= 0x3F;
     value |= (hpm<<LIS3DH_HPM);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG2, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt1Duration()
status_t LIS3DH_SetInt1Duration (LIS3DH_Int1Conf_t id)
Definition at line 1109 of file lis3dh_driver.c.
References LIS3DH_INT1_DURATION, and LIS3DH_WriteReg().
{
     if (id > 127)
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_INT1_DURATION, id) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt1Pin()
status_t LIS3DH_SetInt1Pin (LIS3DH_IntPinConf_t pinConf)
Definition at line 683 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG3, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG3, &value) )
         return MEMS_ERROR;
     value &= 0x00;
     value |= pinConf;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG3, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt1Threshold()
status_t LIS3DH_SetInt1Threshold (u8_t ths)
Definition at line 1091 of file lis3dh_driver.c.
References LIS3DH_INT1_THS, and LIS3DH_WriteReg().
Referenced by configMEMSsensor().
{
     if (ths > 127)
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_INT1_THS, ths) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt2Pin()
status_t LIS3DH_SetInt2Pin (LIS3DH_IntPinConf_t pinConf)
Definition at line 712 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG6, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG6, &value) )
         return MEMS_ERROR;
     value &= 0x00;
     value |= pinConf;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG6, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetInt6D4DConfiguration()
status_t LIS3DH_SetInt6D4DConfiguration (LIS3DH_INT_6D_4D_t ic)
Definition at line 1005 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG5, LIS3DH_D4D_INT1, LIS3DH_INT1_4D_ENABLE, LIS3DH_INT1_6D_4D_DISABLE, LIS3DH_INT1_6D_ENABLE, LIS3DH_INT1_CFG, LIS3DH_INT_6D, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     u8_t value2;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_CFG, &value) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG5, &value2) )
         return MEMS_ERROR;
     if(ic == LIS3DH_INT1_6D_ENABLE) {
         value &= 0xBF;
         value |= (MEMS_ENABLE<<LIS3DH_INT_6D);
         value2 &= 0xFB;
         value2 |= (MEMS_DISABLE<<LIS3DH_D4D_INT1);
     }
     if(ic == LIS3DH_INT1_4D_ENABLE) {
         value &= 0xBF;
         value |= (MEMS_ENABLE<<LIS3DH_INT_6D);
         value2 &= 0xFB;
         value2 |= (MEMS_ENABLE<<LIS3DH_D4D_INT1);
     }
     if(ic == LIS3DH_INT1_6D_4D_DISABLE) {
         value &= 0xBF;
         value |= (MEMS_DISABLE<<LIS3DH_INT_6D);
         value2 &= 0xFB;
         value2 |= (MEMS_DISABLE<<LIS3DH_D4D_INT1);
     }
     if( !LIS3DH_WriteReg(LIS3DH_INT1_CFG, value) )
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG5, value2) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetIntConfiguration()
status_t LIS3DH_SetIntConfiguration (LIS3DH_Int1Conf_t ic)
Definition at line 958 of file lis3dh_driver.c.
References LIS3DH_INT1_CFG, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_CFG, &value) )
         return MEMS_ERROR;
     value &= 0x40;
     value |= ic;
     if( !LIS3DH_WriteReg(LIS3DH_INT1_CFG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetIntMode()
status_t LIS3DH_SetIntMode (LIS3DH_Int1Mode_t ic)
Definition at line 982 of file lis3dh_driver.c.
References LIS3DH_INT1_CFG, LIS3DH_INT_6D, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_INT1_CFG, &value) )
         return MEMS_ERROR;
     value &= 0x3F;
     value |= (int_mode<<LIS3DH_INT_6D);
     if( !LIS3DH_WriteReg(LIS3DH_INT1_CFG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetMode()
status_t LIS3DH_SetMode (LIS3DH_Mode_t md)
Definition at line 362 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG1, LIS3DH_CTRL_REG4, LIS3DH_HR, LIS3DH_LOW_POWER, LIS3DH_LPEN, LIS3DH_NORMAL, LIS3DH_POWER_DOWN, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by initMEMSsensor().
{
     u8_t value;
     u8_t value2;
     static   u8_t ODR_old_value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG1, &value) )
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value2) )
         return MEMS_ERROR;
     if((value & 0xF0)==0)
         value = value | (ODR_old_value & 0xF0); //if it comes from POWERDOWN
     switch(md) {
     case LIS3DH_POWER_DOWN:
         ODR_old_value = value;
         value &= 0x0F;
         break;
     case LIS3DH_NORMAL:
         value &= 0xF7;
         value |= (MEMS_RESET<<LIS3DH_LPEN);
         value2 &= 0xF7;
         value2 |= (MEMS_SET<<LIS3DH_HR);   //set HighResolution_BIT
         break;
     case LIS3DH_LOW_POWER:
         value &= 0xF7;
         value |=  (MEMS_SET<<LIS3DH_LPEN);
         value2 &= 0xF7;
         value2 |= (MEMS_RESET<<LIS3DH_HR); //reset HighResolution_BIT
         break;
     default:
         return MEMS_ERROR;
     }
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG1, value) )
         return MEMS_ERROR;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value2) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetODR()
status_t LIS3DH_SetODR (LIS3DH_ODR_t ov)
Definition at line 229 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG1, LIS3DH_ODR_BIT, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
Referenced by initMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG1, &value) )
         return MEMS_ERROR;
     value &= 0x0f;
     value |= ov<<LIS3DH_ODR_BIT;
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG1, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetSelfTest()
status_t LIS3DH_SetSelfTest (LIS3DH_SelfTest_t st)
Definition at line 509 of file lis3dh_driver.c.
References LIS3DH_CTRL_REG4, LIS3DH_ReadReg(), LIS3DH_ST, and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_CTRL_REG4, &value) )
         return MEMS_ERROR;
     value &= 0xF9;
     value |= (st<<LIS3DH_ST);
     if( !LIS3DH_WriteReg(LIS3DH_CTRL_REG4, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetTemperature()
status_t LIS3DH_SetTemperature (State_t state)
Definition at line 254 of file lis3dh_driver.c.
References LIS3DH_ReadReg(), LIS3DH_TEMP_CFG_REG, LIS3DH_TEMP_EN, and LIS3DH_WriteReg().
Referenced by configMEMSsensor().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_TEMP_CFG_REG, &value) )
         return MEMS_ERROR;
     value &= 0xBF;
     value |= state<<LIS3DH_TEMP_EN;
     if( !LIS3DH_WriteReg(LIS3DH_TEMP_CFG_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetTriggerInt()
status_t LIS3DH_SetTriggerInt (LIS3DH_TrigInt_t tr)
Definition at line 1237 of file lis3dh_driver.c.
References LIS3DH_FIFO_CTRL_REG, LIS3DH_ReadReg(), LIS3DH_TR, and LIS3DH_WriteReg().
{
     u8_t value;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
         return MEMS_ERROR;
     value &= 0xDF;
     value |= (tr<<LIS3DH_TR);
     if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_SetWaterMark()
status_t LIS3DH_SetWaterMark (u8_t wtm)
Definition at line 1260 of file lis3dh_driver.c.
References LIS3DH_FIFO_CTRL_REG, LIS3DH_ReadReg(), and LIS3DH_WriteReg().
{
     u8_t value;
     if(wtm > 31)
         return MEMS_ERROR;
     if( !LIS3DH_ReadReg(LIS3DH_FIFO_CTRL_REG, &value) )
         return MEMS_ERROR;
     value &= 0xE0;
     value |= wtm;
     if( !LIS3DH_WriteReg(LIS3DH_FIFO_CTRL_REG, value) )
         return MEMS_ERROR;
     return MEMS_SUCCESS;
 }
LIS3DH_WriteReg()
u8_t LIS3DH_WriteReg (u8_t Reg, u8_t Data)
Definition at line 71 of file lis3dh_driver.c.
References _i2c_xfer().
Referenced by LIS3DH_FIFOModeEnable(), LIS3DH_HPFAOI1Enable(), LIS3DH_HPFAOI2Enable(), LIS3DH_HPFClickEnable(), LIS3DH_Int1LatchEnable(), LIS3DH_SetADCAux(), LIS3DH_SetAxis(), LIS3DH_SetBDU(), LIS3DH_SetBLE(), LIS3DH_SetClickCFG(), LIS3DH_SetClickLATENCY(), LIS3DH_SetClickLIMIT(), LIS3DH_SetClickTHS(), LIS3DH_SetClickWINDOW(), LIS3DH_SetFilterDataSel(), LIS3DH_SetFullScale(), LIS3DH_SetHPFCutOFF(), LIS3DH_SetHPFMode(), LIS3DH_SetInt1Duration(), LIS3DH_SetInt1Pin(), LIS3DH_SetInt1Threshold(), LIS3DH_SetInt2Pin(), LIS3DH_SetInt6D4DConfiguration(), LIS3DH_SetIntConfiguration(), LIS3DH_SetIntMode(), LIS3DH_SetMode(), LIS3DH_SetODR(), LIS3DH_SetSelfTest(), LIS3DH_SetSPIInterface(), LIS3DH_SetTemperature(), LIS3DH_SetTriggerInt(), and LIS3DH_SetWaterMark().
{
     //To be completed with either I2c or SPI writing function
     //i.e. SPI_Mems_Write_Reg(WriteAddr, Data);
     _i2c_xfer (0, WriteAddr, Data, 0);
     return 1;
 }