BEL3 ESS task: gtk_GUI/menucallbacks.c File Reference
menucallbacks.c File Reference
menucallbacks 3Dacceltask GUI
#include "menucallbacks.h"
Functions
void fileName (GtkWidget *widget, gpointer data)
prepare filename for logging
void entryPollTime (GtkWidget *widget, gpointer data)
get poll time from entry
void entryXtrigger (GtkWidget *widget, gpointer data)
get X trigger from entry
void entryYtrigger (GtkWidget *widget, gpointer data)
get Y trigger from entry
void entryZtrigger (GtkWidget *widget, gpointer data)
get Z trigger from entry
void readRadioUSB (GtkWidget *button, gpointer *data)
read radio buttons for UART connection
guint wait (gpointer data)
simple wait function button feedback XMC
guint quitButton (gpointer data)
timer to quit app safely
guint buttonFeedback (gpointer data)
timer to highlight pressed button
guint freeFallLabel (gpointer data)
timer to highlight freefall label
guint waitSendTerminal (gpointer data)
timer for output and request terminal function
guint waitSendnoTerminal (gpointer data)
timer for output and request function
guint waitSendPython (gpointer data)
timer for output and request function Python
guint safeStop (gpointer data)
timer for safe UART stop
guint safeEnd (gpointer data)
timer for safe UART end
guint safeClose (gpointer data)
timer for safe UART close
void connectSerial (GtkButton *button, gpointer data)
function connect UART
void requestData (gpointer data)
function request data from XMC UART
void servoConnector (gpointer data)
function servo connector
void averageConnector (gpointer data)
function average choose
void statisticConnector (GtkButton *button, gpointer data)
function statistic request from XMC
void servo (GtkWidget *button, gpointer data)
function toggle servo on off
void average (GtkWidget *button, gpointer data)
function toggle signal averaging
void dataTransmission (GtkButton *button, gpointer data)
function for timed data request
void pythonConnector (GtkButton *button, gpointer data)
function to start python script plotter
void pythonSpriteConnector (GtkButton *button, gpointer data)
function to start python sprite
void rawProtocolData (GtkButton *button, gpointer data)
function to show data in terminal window
void saveData (GtkButton *button, gpointer data)
function to toggle protocol on off
void rawProtocolDataTimed (gpointer data)
main function to receive timed data from XMC and handle protocol etc.
void about (GSimpleAction *action, GVariant *parameter, gpointer data)
about message dialog
void help (GSimpleAction *action, GVariant *parameter, gpointer data)
help message dialog text concenation
void messageDialog (GSimpleAction *action, GVariant *parameter, gpointer data, gchar *showText)
help message dialog
void quit (GSimpleAction *action, GVariant *parameter, gpointer data)
quit dialog
unsigned int getInteger (char *input, int *numInteger)
function to convert string to integer
unsigned int getDouble (char *input, double *numDouble)
function to convert string to double
Detailed Description
menucallbacks 3Dacceltask GUI
Version
v1.0
Date
Jan 2018
Author
Egermann, Resch
Definition in file menucallbacks.c.
Function Documentation
about()
void about (GSimpleAction * action, GVariant * parameter, gpointer data)
about message dialog
Definition at line 1184 of file menucallbacks.c.
References messageDialog().
 {
     widgets *a = (widgets *) data;
     messageDialog(action, NULL, (gpointer) a, "BEL3 ESS accelerometer task\n\nWerner Egermann, Helmut Resch");
 }
average()
void average (GtkWidget * button, gpointer data)
function toggle signal averaging
Definition at line 680 of file menucallbacks.c.
References widgets::average, averageConnector(), and widgets::button.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(button)))
     {
         g_print("%s toggled on\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[8]), "ANGLE average");
         a->average = 1;
     }
     else
     {
         g_print("%s toggled off\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[8]), "PWM average");
         a->average = 0;
     }
     averageConnector((gpointer) a);
 }
averageConnector()
void averageConnector (gpointer data)
function average choose
Definition at line 602 of file menucallbacks.c.
References widgets::average, widgets::radioButtonUSBstate, RS232_flushTX(), RS232_SendBuf(), RS232_SendByte(), widgets::sendSerial, and widgets::transmission.
Referenced by average().
 {
     widgets *a = (widgets *) data;
     unsigned char requestAveragePWM[] = "#AVG,p";
     unsigned char requestAverageANGLE[] = "#AVG,a";
     a->sendSerial = FALSE;
     if (a->average == 0)
     {
         a->average = 1;
         RS232_flushTX(a->radioButtonUSBstate);
         RS232_SendBuf(a->radioButtonUSBstate, requestAveragePWM, (int)sizeof(requestAveragePWM));
         RS232_SendByte(a->radioButtonUSBstate, '\r');
     }
     else if (a->average == 1)
     {
         a->average = 0;
         RS232_flushTX(a->radioButtonUSBstate);
         RS232_SendBuf(a->radioButtonUSBstate, requestAverageANGLE, (int)sizeof(requestAverageANGLE));
         RS232_SendByte(a->radioButtonUSBstate, '\r');
     }
     if (a->transmission == TRUE)
     {
         a->sendSerial = TRUE;
     }
 }
buttonFeedback()
guint buttonFeedback (gpointer data)
timer to highlight pressed button
Definition at line 328 of file menucallbacks.c.
References widgets::buttonID, widgets::buttonXMC, and widgets::label.
Referenced by rawProtocolDataTimed().
 {
     widgets *a = (widgets *) data;
     if(a->buttonID == 1)
     {
         gtk_label_set_label((GtkLabel*)a->label[16], "<span foreground='white' weight='ultrabold' font='16'>  BUTTON 1 </span>");
     }
     else if(a->buttonID == 2)
     {
         gtk_label_set_label((GtkLabel*)a->label[17], "<span foreground='white' weight='ultrabold' font='16'>  BUTTON 2 </span>");
     }
     return a->buttonXMC;
 }
connectSerial()
void connectSerial (GtkButton * button, gpointer data)
function connect UART
Definition at line 493 of file menucallbacks.c.
References BAUD, widgets::bufferStatusBar, widgets::button, widgets::connectionStatus, widgets::entry, direction::i, widgets::id, widgets::label, widgets::radioButtonUSBstate, widgets::radioUSB, RS232_flushTX(), RS232_OpenComport(), RS232_SendBuf(), RS232_SendByte(), safeStop(), widgets::safeWaitStop, widgets::sendSerial, widgets::statusBar, and UARTWAIT.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     char mode[]= {'8','N','1', 0};
     const char openComPortError[] = "ERROR opening COM port";
     const char openComPortSuccess[] = "SUCCESS opening COM port";
     unsigned char requestConnection[] = "#CON,";
     gint i = 0;
     if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(button)))
     {
         g_print("%s toggled on\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[0]), "CONNECTION on");
         if(RS232_OpenComport(a->radioButtonUSBstate, BAUD, mode))
         {
             snprintf(a->bufferStatusBar, sizeof(openComPortError)+1, "%s", openComPortError);
             gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
             a->connectionStatus = 0;
         }
         else
         {
             snprintf(a->bufferStatusBar, sizeof(openComPortSuccess)+1, "%s", openComPortSuccess);
             gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
             a->connectionStatus = 1;
             for (i = 1; i < 7; i++)
             {
                 gtk_widget_set_sensitive (GTK_WIDGET (a->button[i]), TRUE);
             }
             for (i = 0; i < 5; i++)
             {
                 gtk_widget_set_sensitive (GTK_WIDGET (a->radioUSB[i]), FALSE);
             }
             gtk_widget_set_sensitive (GTK_WIDGET (a->entry[0]), FALSE);
             RS232_flushTX(a->radioButtonUSBstate);
             RS232_SendBuf(a->radioButtonUSBstate, requestConnection, (int)sizeof(requestConnection));
             RS232_SendByte(a->radioButtonUSBstate, '\r');
         }
     }
     else
     {
         g_print("%s toggled off\n", gtk_button_get_label(GTK_BUTTON(button)));
         a->connectionStatus = 0;
         gtk_button_set_label(GTK_BUTTON(a->button[0]), "CONNECTION off");
         gtk_label_set_label((GtkLabel*)a->label[16], "<span foreground='white' weight='ultrabold' font='16'> BUTTON 1 </span>");
         a->sendSerial = FALSE;
         a->safeWaitStop = FALSE;
         g_timeout_add (UARTWAIT, (GSourceFunc) safeStop, (gpointer) a);
     }
 }
dataTransmission()
void dataTransmission (GtkButton * button, gpointer data)
function for timed data request
Definition at line 704 of file menucallbacks.c.
References widgets::button, widgets::entry, direction::i, widgets::pollTimeSensor, widgets::sendSerial, widgets::transmission, and waitSendnoTerminal().
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gint i = 0;
     for (i = 2; i < 5; i++)
     {
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[i]), FALSE);
     }
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[3]), TRUE);
     if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(button)))
     {
         g_print("%s toggled on\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[3]), "TRANSMISSION on");
         a->transmission = TRUE;
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[1]), TRUE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[4]), FALSE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[5]), FALSE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->entry[4]), TRUE);
         a->sendSerial = TRUE;
         g_timeout_add (a->pollTimeSensor, (GSourceFunc) waitSendnoTerminal, (gpointer) a);
     }
     else
     {
         g_print("%s toggled off\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[3]), "TRANSMISSION off");
         a->transmission = FALSE;
         a->sendSerial = FALSE;
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[7]), FALSE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[1]), FALSE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[4]), TRUE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[5]), TRUE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->entry[4]), FALSE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[8]), FALSE);
     }
 }
entryPollTime()
void entryPollTime (GtkWidget * widget, gpointer data)
get poll time from entry
Definition at line 62 of file menucallbacks.c.
References widgets::bufferStatusBar, widgets::entry, getInteger(), widgets::id, POLLMAX, POLLMIN, widgets::pollTimeSensor, and widgets::statusBar.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gchar *buffer;
     gint rv = 0;
     buffer = (gchar*) gtk_entry_get_text (GTK_ENTRY (a->entry[0]));
     rv = getInteger(buffer, &a->pollTimeSensor);
     if (rv == 1)
     {
         g_sprintf (a->bufferStatusBar, "you did not enter a correct number");
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         return;
     }
     if (a->pollTimeSensor < POLLMIN)
     {
         g_sprintf (a->bufferStatusBar, "you have chosen %d ms poll time, lower limit is 10 ms, this is now set", a->pollTimeSensor);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->pollTimeSensor = POLLMIN;
     }
     else if (a->pollTimeSensor > POLLMAX)
     {
         g_sprintf (a->bufferStatusBar, "you have chosen %d ms poll time, upper limit is 1000 ms, this is now set", a->pollTimeSensor);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->pollTimeSensor = POLLMAX;
     }
     else
     {
         g_sprintf (a->bufferStatusBar, "you have chosen %d ms poll time", a->pollTimeSensor);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
 }
entryXtrigger()
void entryXtrigger (GtkWidget * widget, gpointer data)
get X trigger from entry
Definition at line 101 of file menucallbacks.c.
References widgets::acceltriggerX, widgets::bufferStatusBar, widgets::entry, getDouble(), GMAX, GMIN, widgets::id, and widgets::statusBar.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gchar *buffer;
     gint rv = 0;
     buffer = (gchar*) gtk_entry_get_text (GTK_ENTRY (a->entry[1]));
     rv = getDouble(buffer, &a->acceltriggerX);
     if (rv == 1)
     {
         g_sprintf (a->bufferStatusBar, "you did not enter a correct number");
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         return;
     }
     if (a->acceltriggerX < GMIN)
     {
         g_sprintf (a->bufferStatusBar, "minimum %.2fg set", GMIN);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->acceltriggerX = GMIN;
     }
     else if (a->acceltriggerX > GMAX)
     {
         g_sprintf (a->bufferStatusBar, "maximum %.2fg set", GMAX);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->acceltriggerX = GMAX;
     }
     else
     {
         g_sprintf (a->bufferStatusBar, "you have chosen %.2f g trigger for X", a->acceltriggerX);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
 }
entryYtrigger()
void entryYtrigger (GtkWidget * widget, gpointer data)
get Y trigger from entry
Definition at line 140 of file menucallbacks.c.
References widgets::acceltriggerY, widgets::bufferStatusBar, widgets::entry, getDouble(), GMAX, GMIN, widgets::id, and widgets::statusBar.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gchar *buffer;
     gint rv = 0;
     buffer = (gchar*) gtk_entry_get_text (GTK_ENTRY (a->entry[2]));
     rv = getDouble(buffer, &a->acceltriggerY);
     if (rv == 1)
     {
         g_sprintf (a->bufferStatusBar, "you did not enter a correct number");
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         return;
     }
     if (a->acceltriggerY < GMIN)
     {
         g_sprintf (a->bufferStatusBar, "minimum %.2fg set", GMIN);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->acceltriggerY = GMIN;
     }
     else if (a->acceltriggerY > GMAX)
     {
         g_sprintf (a->bufferStatusBar, "maximum %.2fg set", GMAX);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->acceltriggerY = GMAX;
     }
     else
     {
         g_sprintf (a->bufferStatusBar, "you have chosen %.2f g trigger for X", a->acceltriggerY);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
 }
entryZtrigger()
void entryZtrigger (GtkWidget * widget, gpointer data)
get Z trigger from entry
Definition at line 179 of file menucallbacks.c.
References widgets::acceltriggerX, widgets::acceltriggerZ, widgets::bufferStatusBar, widgets::entry, getDouble(), GMAX, GMIN, widgets::id, and widgets::statusBar.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gchar *buffer;
     gint rv = 0;
     buffer = (gchar*) gtk_entry_get_text (GTK_ENTRY (a->entry[3]));
     rv = getDouble(buffer, &a->acceltriggerZ);
     if (rv == 1)
     {
         g_sprintf (a->bufferStatusBar, "you did not enter a correct number");
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         return;
     }
     if (a->acceltriggerZ < GMIN)
     {
         g_sprintf (a->bufferStatusBar, "minimum %.2fg set", GMIN);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->acceltriggerX = GMIN;
     }
     else if (a->acceltriggerZ > GMAX)
     {
         g_sprintf (a->bufferStatusBar, "maximum %.2fg set", GMAX);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
         a->acceltriggerZ = GMAX;
     }
     else
     {
         g_sprintf (a->bufferStatusBar, "you have chosen %.2f g trigger for X", a->acceltriggerZ);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
 }
fileName()
void fileName (GtkWidget * widget, gpointer data)
prepare filename for logging
Definition at line 19 of file menucallbacks.c.
References widgets::bufferStatusBar, widgets::button, widgets::entry, widgets::fileName, widgets::id, widgets::statusBar, and widgets::transmission.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gchar *buffer;
     gchar timeZone[100];
     TM *timeStamp, timeTemp;
     time_t timeEpoch;
     // prepare timestamp
     timeEpoch = time(NULL);
     timeStamp = localtime_r(&timeEpoch, &timeTemp);
     // prepare save and log string
     if (strftime(timeZone, sizeof(timeZone), "%Y.%B.%d_%T", timeStamp) == 0)
     {
         g_print ("strftime returned 0");
         return;
     }
     buffer = (gchar*) gtk_entry_get_text (GTK_ENTRY (a->entry[4]));
     g_sprintf(a->fileName, "%s_%s.log", timeZone, buffer);
     g_print("%s\n", a->fileName);
     g_sprintf (a->bufferStatusBar, "filename in local folder %s", a->fileName);
     gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     if (a->transmission == TRUE)
     {
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[7]), TRUE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->entry[4]), FALSE);
     }
     else
     {
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[7]), FALSE);
         gtk_widget_set_sensitive (GTK_WIDGET (a->entry[4]), TRUE);
     }
 }
freeFallLabel()
guint freeFallLabel (gpointer data)
timer to highlight freefall label
Definition at line 348 of file menucallbacks.c.
References widgets::freeFallLabel, widgets::label, widgets::xfree, widgets::yfree, and widgets::zfree.
Referenced by rawProtocolDataTimed().
 {
     widgets *a = (widgets *) data;
     gtk_label_set_label((GtkLabel*)a->label[15], "<span foreground='white' weight='ultrabold' font='20'> SAFE </span>");
     a->xfree = 0;
     a->yfree = 0;
     a->zfree = 0;
     return a->freeFallLabel;
 }
getDouble()
unsigned int getDouble (char * input, double * numDouble)
function to convert string to double
Parameters
input string and output double pointer
Returns
0 on success, 1 on error
Definition at line 1291 of file menucallbacks.c.
Referenced by entryXtrigger(), entryYtrigger(), and entryZtrigger().
 {
     long double number = 0;
     char *pointToEnd = NULL;
     number = strtod(input, &pointToEnd);
     if(*pointToEnd != '\0')
     {
         return 1;
     }
     else
     {
         *numDouble = (double)number;
         return 0;
     }
 }
getInteger()
unsigned int getInteger (char * input, int * numInteger)
function to convert string to integer
Parameters
input string and output integer pointer
Returns
0 on success, 1 on error
Definition at line 1268 of file menucallbacks.c.
Referenced by entryPollTime(), and rawProtocolDataTimed().
 {
     unsigned long int number = 0;
     char *pointToEnd = NULL;
     number = strtoul(input, &pointToEnd, 0);
     if(*pointToEnd != '\0')
     {
         return 1;
     }
     else
     {
         *numInteger = (int)number;
         return 0;
     }
 }
help()
void help (GSimpleAction * action, GVariant * parameter, gpointer data)
help message dialog text concenation
Definition at line 1195 of file menucallbacks.c.
References messageDialog().
 {
     widgets *a = (widgets *) data;
     const char connectionText[] = "CONNECTION - choose your /dev/ttyUSB and connect to XMC\n\n";
     const char statisticText[] = "STATISTIC - receive statistic from XMC with next transmission\n\n";
     const char saveText[] = "SAVE - enter a filename after activating transmission\n\n";
     const char terminalText[] = "TERMINAL - simple terminal for raw data, close window to exit\n\n";
     const char transmissionText[] = "TRANSMISSION - starts and ends transmission and connected tasks\n\n";
     const char diagramsText[] = "DIAGRAMS - Python connector diagrams X Y Z acceleration\n\n";
     const char spritesText[]  = "SPRITES - Python connector sprites for ROLL and PITCH\n\n";
     const char servoText[] = "SERVO - starts stops the servos connected to XMC\n\n";
     const char enterpolltimeText[] = "polltime in milliseconds - from 10 to 1000 possible\n\n";
     const char triggeraccText[] = "trigger g-force for every axis can be set and is triggered\n\n";
     const char buttonText[] = "buttons highlight the pressed buttons on XMC\n\n";
     gchar messageText[1000];
     g_sprintf(messageText, "%s%s%s%s%s%s%s%s%s%s%s", connectionText, statisticText, saveText, terminalText, transmissionText, diagramsText, spritesText, servoText, enterpolltimeText, triggeraccText, buttonText);
     messageDialog(action, NULL, (gpointer) a, messageText);
 }
messageDialog()
void messageDialog (GSimpleAction * action, GVariant * parameter, gpointer data, gchar * showText)
help message dialog
Definition at line 1220 of file menucallbacks.c.
References widgets::window.
Referenced by about(), and help().
 {
     widgets *a = (widgets *) data;
     const gchar *name;
     GtkWidget *dialog;
     name = g_action_get_name (G_ACTION (action));
     dialog = gtk_message_dialog_new (GTK_WINDOW (a->window), GTK_DIALOG_DESTROY_WITH_PARENT|GTK_DIALOG_MODAL, GTK_MESSAGE_INFO, GTK_BUTTONS_OK, "%s\n\n%s", name, showText);
     g_signal_connect (dialog, "response", G_CALLBACK (gtk_widget_destroy), NULL);
     gtk_widget_show (dialog);
 }
pythonConnector()
void pythonConnector (GtkButton * button, gpointer data)
function to start python script plotter
Definition at line 746 of file menucallbacks.c.
References widgets::button, widgets::pollTimeSensor, widgets::radioButtonUSBstate, widgets::sendSerial, and waitSendPython().
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     char pythonCall[100];
     g_sprintf(pythonCall, "python3 ../python/protocol_plotter.py %d &", a->radioButtonUSBstate);
     system(pythonCall);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[2]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[3]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[5]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[6]), FALSE);
     a->sendSerial = TRUE;
     g_timeout_add (a->pollTimeSensor, (GSourceFunc) waitSendPython, (gpointer) a);
 }
pythonSpriteConnector()
void pythonSpriteConnector (GtkButton * button, gpointer data)
function to start python sprite
Definition at line 768 of file menucallbacks.c.
References widgets::button, widgets::pollTimeSensor, widgets::radioButtonUSBstate, widgets::sendSerial, and waitSendPython().
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     char pythonCall[100];
     g_sprintf(pythonCall, "python3 ../python/direction.py %d &", a->radioButtonUSBstate);
     system(pythonCall);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[2]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[3]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[4]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[6]), FALSE);
     a->sendSerial = TRUE;
     g_timeout_add (a->pollTimeSensor, (GSourceFunc) waitSendPython, (gpointer) a);
 }
quit()
void quit (GSimpleAction * action, GVariant * parameter, gpointer data)
quit dialog
Definition at line 1237 of file menucallbacks.c.
References widgets::app, widgets::connectionStatus, widgets::id, quitButton(), QUITWAIT, safeStop(), widgets::safeWaitStop, widgets::sendSerial, widgets::statusBar, and UARTWAIT.
 {
     widgets *a = (widgets *) data;
     g_printf("shutting down connection to XMC...\n");
     gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, "shutting down connection to XMC for safe exit...");
     // necessary shutdown procedure
     if (a->connectionStatus == 1)
     {
         a->sendSerial = FALSE;
         a->safeWaitStop = FALSE;
         g_timeout_add (UARTWAIT, (GSourceFunc) safeStop, (gpointer) a);
         a->quitButton = FALSE;
         g_timeout_add (QUITWAIT, (GSourceFunc) quitButton, (gpointer) a);
     }
     else
     {
         g_application_quit(G_APPLICATION (a->app));
     }
 }
quitButton()
guint quitButton (gpointer data)
timer to quit app safely
Definition at line 315 of file menucallbacks.c.
References widgets::app, and widgets::quitButton.
Referenced by quit().
 {
     widgets *a = (widgets *) data;
     g_application_quit(G_APPLICATION (a->app));
     return a->quitButton;
 }
rawProtocolData()
void rawProtocolData (GtkButton * button, gpointer data)
function to show data in terminal window
Definition at line 790 of file menucallbacks.c.
References widgets::buffer, widgets::button, direction::i, widgets::line, widgets::pollTimeSensor, widgets::scroll, widgets::sendSerial, widgets::terminalwindow, widgets::transmission, widgets::view, and waitSendTerminal().
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gint i = 0;
     a->transmission = TRUE;
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[3]), FALSE);
     for (i = 2; i < 8; i++)
     {
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[i]), FALSE);
     }
     strcpy(a->line, ".");
     a->terminalwindow = gtk_window_new(GTK_WINDOW_TOPLEVEL);
     gtk_window_set_title (GTK_WINDOW (a->terminalwindow), "Terminal window");
     gtk_container_set_border_width (GTK_CONTAINER (a->terminalwindow), 0);
     gtk_widget_set_size_request (a->terminalwindow, 400, 800);
     gtk_window_set_resizable(GTK_WINDOW (a->terminalwindow), TRUE);
     a->buffer = gtk_text_buffer_new (NULL);
     gtk_text_buffer_create_tag (a->buffer, "not_editable",  "editable", FALSE, NULL);
     gtk_text_buffer_create_tag (a->buffer, "word_wrap", "wrap_mode", GTK_WRAP_WORD, NULL);
     a->view = gtk_text_view_new_with_buffer (a->buffer);
     a->scroll = gtk_scrolled_window_new (NULL, NULL);
     gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (a->scroll), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
     gtk_container_add (GTK_CONTAINER (a->scroll), a->view);
     gtk_container_add (GTK_CONTAINER (a->terminalwindow), a->scroll);
     gtk_widget_show_all(GTK_WIDGET(a->terminalwindow));
     a->sendSerial = TRUE;
     g_timeout_add (a->pollTimeSensor, (GSourceFunc) waitSendTerminal, (gpointer) a);
 }
rawProtocolDataTimed()
void rawProtocolDataTimed (gpointer data)
main function to receive timed data from XMC and handle protocol etc.
Definition at line 853 of file menucallbacks.c.
References widgets::accelerationXdouble, widgets::accelerationXout, widgets::accelerationYdouble, widgets::accelerationYout, widgets::accelerationZdouble, widgets::accelerationZout, widgets::acceltriggerX, widgets::acceltriggerY, widgets::acceltriggerZ, widgets::box, buttonFeedback(), widgets::buttonID, BUTTONWAIT, widgets::buttonXMC, widgets::errorOut, widgets::fileName, widgets::freeFallLabel, freeFallLabel(), FREEFALLTIME, FREELO, G, GDIVIDER, getInteger(), widgets::grid, direction::i, widgets::image, widgets::label, widgets::line, OSBUFFER, widgets::packagesOut, PI, widgets::pitch, widgets::pitchOut, widgets::position6D, widgets::position6Dint, widgets::radioButtonUSBstate, widgets::restartPackagesOut, widgets::roll, widgets::rollOut, RS232_flushRX(), RS232_PollComport(), widgets::saveOutgoing, widgets::tiltX, widgets::tiltXout, widgets::tiltY, widgets::tiltYout, widgets::tiltZ, widgets::tiltZout, WAIT, widgets::wait, wait(), widgets::xfree, widgets::yfree, and widgets::zfree.
Referenced by waitSendnoTerminal(), and waitSendTerminal().
 {
     widgets *a = (widgets *) data;
     unsigned char buf[OSBUFFER] = { 0 };
     int n = 0, i = 0;
     FILE *saveFile = NULL;
     gchar accelerationX[8], accelerationY[8], accelerationZ[8], packages[11], error[4], packagesOut[11];
     gint accelerationXint, accelerationYint, accelerationZint, packagesInt, packagesOutInt, errorInt;
     TM *timeStamp, timeTemp;
     TIMEVAL tmnow;
     time_t timeEpoch;
     gchar timeZoneTemp[100], timeZone[100];
     // prepare timestamp
     timeEpoch = time(NULL);
     timeStamp = localtime_r(&timeEpoch, &timeTemp);
     gettimeofday(&tmnow, NULL);
     // prepare save and log string
     if (strftime(timeZoneTemp, sizeof(timeZoneTemp), "%A|%d|%B|%Y|%T", timeStamp) == 0)
     {
         g_print ("strftime returned 0");
         return;
     }
     // add milliseconds
     g_sprintf(timeZone, "%s.%06d", timeZoneTemp, (int)tmnow.tv_usec);
     // read data from UART
     memset (&buf, 0, sizeof (buf));
     n = RS232_PollComport(a->radioButtonUSBstate, buf, (OSBUFFER-1));
     RS232_flushRX(a->radioButtonUSBstate);
     if (n > 0)
     {
         g_sprintf(a->line, "%s", (char *)buf);
     }
     for (i = 0; i < strlen(a->line); i++)
     {
         if (a->line[i] == '\n' || a->line[i] == '\r')
         {
             a->line[i] = '\0';
             break;
         }
     }
     // cut 6D position from received string
     if (strncpy(a->position6D, a->line+1, 3) != a->position6D)
     {
         g_print("strncpy1 error\n");
     }
     if (strncmp(a->position6D, "STA", 3) == 0)
     {
         // decode statistic package
         if (strncpy(packages, a->line+5, 10) != packages)
         {
             g_print("strncpy error\n");
         }
         packages[10] = '\0';
         getInteger(packages, &packagesInt);
         g_sprintf(a->packagesOut, "total\t%d", packagesInt);
         if (strncpy(error, a->line+16, 3) != error)
         {
             g_print("strncpy error\n");
         }
         error[3] = '\0';
         getInteger(error, &errorInt);
         g_sprintf(a->errorOut, "errors\t%d", errorInt);
         if (strncpy(packagesOut, a->line+20, 10) != packagesOut)
         {
             g_print("strncpy error\n");
         }
         packagesOut[10] = '\0';
         getInteger(packagesOut, &packagesOutInt);
         g_sprintf(a->restartPackagesOut, "sensor\t%d", packagesOutInt);
         gtk_label_set_label((GtkLabel*)a->label[4], a->restartPackagesOut);
         gtk_label_set_label((GtkLabel*)a->label[13], a->packagesOut);
         gtk_label_set_label((GtkLabel*)a->label[14], a->errorOut);
         return;
     }
     else if (strncmp(a->position6D, "BUT", 3) == 0)
     {
         // decode button from XMC
         a->wait = FALSE;
         if(a->line[5] == '1')
         {
             gtk_label_set_label((GtkLabel*)a->label[16], "<span foreground='white' background='blue' weight='ultrabold' font='16'> BUTTON 1 </span>");
             a->buttonID = 1;
             a->buttonXMC = FALSE;
             g_timeout_add (BUTTONWAIT, (GSourceFunc) buttonFeedback, (gpointer) a);
         }
         else if(a->line[5] == '2')
         {
             gtk_label_set_label((GtkLabel*)a->label[17], "<span foreground='white' background='blue' weight='ultrabold' font='16'> BUTTON 2 </span>");
             a->buttonID = 2;
             a->buttonXMC = FALSE;
             g_timeout_add (BUTTONWAIT, (GSourceFunc) buttonFeedback, (gpointer) a);
         }
         g_timeout_add (WAIT, (GSourceFunc) wait, (gpointer) a);
     }
     else
     {
         gtk_label_set_label((GtkLabel*)a->label[0], a->position6D);
         // decode acceleration raw data
         if (strncpy(accelerationX, a->line+5, 6) != accelerationX)
         {
             g_print("strncpy2 error\n");
         }
         accelerationX[6] = '\0';
         getInteger(accelerationX, &accelerationXint);
         a->accelerationXdouble = accelerationXint / GDIVIDER;
         g_sprintf(a->accelerationXout, "accelX %7.3f g", a->accelerationXdouble);
         gtk_label_set_label((GtkLabel*)a->label[1], a->accelerationXout);
         if (strncpy(accelerationY, a->line+12, 6) != accelerationY)
         {
             g_print("strncpy3 error\n");
         }
         accelerationY[6] = '\0';
         getInteger(accelerationY, &accelerationYint);
         a->accelerationYdouble = accelerationYint / GDIVIDER;
         g_sprintf(a->accelerationYout, "accelY %7.3f g", a->accelerationYdouble);
         gtk_label_set_label((GtkLabel*)a->label[2], a->accelerationYout);
         if (strncpy(accelerationZ, a->line+19, 6) != accelerationZ)
         {
             g_print("strncpy4 error\n");
         }
         accelerationZ[6] = '\0';
         getInteger(accelerationZ, &accelerationZint);
         a->accelerationZdouble = accelerationZint / GDIVIDER;
         g_sprintf(a->accelerationZout, "accelZ %7.3f g", a->accelerationZdouble);
         gtk_label_set_label((GtkLabel*)a->label[3], a->accelerationZout);
         // calculate all angles
         a->tiltX = asin(a->accelerationXdouble/G) * 180 / PI;
         a->tiltY = asin(a->accelerationYdouble/G) * 180 / PI;
         a->tiltZ = asin(a->accelerationZdouble/G) * 180 / PI;
         a->pitch = atan(a->accelerationXdouble/(sqrt((a->accelerationYdouble*a->accelerationYdouble)+(a->accelerationZdouble*a->accelerationZdouble)))) * 180 / PI;
         a->roll = atan(a->accelerationYdouble/(sqrt((a->accelerationXdouble*a->accelerationXdouble)+(a->accelerationZdouble*a->accelerationZdouble)))) * 180 / PI;
         // save if requested
         if (a->saveOutgoing == 1)
         {
             saveFile = fopen(a->fileName, "a");
             if (fprintf(saveFile, "%lu|%s|%s|%f|%f|%f|%f|%f|%f|%f|%f\n", timeEpoch, timeZone, a->position6D, a->accelerationXdouble, a->accelerationYdouble, a->accelerationZdouble, a->tiltX, a->tiltY, a->tiltZ, a->pitch, a->roll) < 1)
             {
                 g_print ("problems writing save file\n");
                 fclose(saveFile);
                 return;
             }
             fclose(saveFile);
         }
         // show values on GUI
         g_sprintf(a->tiltXout, "tiltX %6.2f ", a->tiltX);
         g_sprintf(a->tiltYout, "tiltY %6.2f ", a->tiltY);
         g_sprintf(a->tiltZout, "tiltZ %6.2f ", a->tiltZ);
         g_sprintf(a->pitchOut, "pitch %6.2f ", a->pitch);
         g_sprintf(a->rollOut, "roll  %6.2f ", a->roll);
         gtk_label_set_label((GtkLabel*)a->label[5], a->tiltXout);
         gtk_label_set_label((GtkLabel*)a->label[6], a->tiltYout);
         gtk_label_set_label((GtkLabel*)a->label[7], a->tiltZout);
         gtk_label_set_label((GtkLabel*)a->label[8], a->pitchOut);
         gtk_label_set_label((GtkLabel*)a->label[9], a->rollOut);
         // change picture for 6D
         if (strncmp(a->position6D, "TOP", 3) == 0)
         {
             a->position6Dint = 1;
         }
         else if (strncmp(a->position6D, "BOT", 3) == 0)
         {
             a->position6Dint = 2;
         }
         else if (strncmp(a->position6D, "DDX", 3) == 0)
         {
             a->position6Dint = 3;
         }
         else if (strncmp(a->position6D, "DSX", 3) == 0)
         {
             a->position6Dint = 4;
         }
         else if (strncmp(a->position6D, "UDX", 3) == 0)
         {
             a->position6Dint = 5;
         }
         else if (strncmp(a->position6D, "USX", 3) == 0)
         {
             a->position6Dint = 6;
         }
         else
         {
             a->position6Dint = 0;
         }
         switch (a->position6Dint)
         {
         case (0):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/ALL.png");
             break;
         }
         case (1):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/TOP.png");
             break;
         }
         case (2):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/BOT.png");
             break;
         }
         case (3):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/DDX.png");
             break;
         }
         case (4):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/DSX.png");
             break;
         }
         case (5):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/UDX.png");
             break;
         }
         case (6):
         {
             a->image[1] = gtk_image_new_from_file("./pictures/USX.png");
             break;
         }
         default:
         {
             a->image[1] = gtk_image_new_from_file("./pictures/ALL.png");
             break;
         }
         }
         gtk_container_remove(GTK_CONTAINER(a->grid), a->box[0]);
         a->box[0] = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
         gtk_grid_attach(GTK_GRID (a->grid), a->box[0], 3, 0, 2, 5);
         gtk_box_pack_start(GTK_BOX(a->box[0]), a->image[1], FALSE, FALSE, 0);
         gtk_widget_set_halign(GTK_WIDGET(a->box[0]), GTK_ALIGN_CENTER);
         gtk_widget_set_valign(GTK_WIDGET(a->box[0]), GTK_ALIGN_CENTER);
         gtk_widget_show_all(a->grid);
         // set trigger labels
         if (fabs(a->accelerationXdouble) > a->acceltriggerX)
         {
             gtk_label_set_label((GtkLabel*)a->label[10], "<span foreground='white' background='red' weight='ultrabold' font='20'> X  ALARM  </span>");
         }
         else
         {
             gtk_label_set_label((GtkLabel*)a->label[10], "<span foreground='white' background='green' weight='ultrabold' font='20'> X TRIGGER </span>");
         }
         if (fabs(a->accelerationYdouble) > a->acceltriggerY)
         {
             gtk_label_set_label((GtkLabel*)a->label[11], "<span foreground='white' background='red' weight='ultrabold' font='20'> Y  ALARM  </span>");
         }
         else
         {
             gtk_label_set_label((GtkLabel*)a->label[11], "<span foreground='white' background='green' weight='ultrabold' font='20'> Y TRIGGER </span>");
         }
         if (fabs(a->accelerationZdouble) > a->acceltriggerZ)
         {
             gtk_label_set_label((GtkLabel*)a->label[12], "<span foreground='white' background='red' weight='ultrabold' font='20'> Z  ALARM  </span>");
         }
         else
         {
             gtk_label_set_label((GtkLabel*)a->label[12], "<span foreground='white' background='green' weight='ultrabold' font='20'> Z TRIGGER </span>");
         }
         // simple freefall detection
         if (fabs(a->accelerationXdouble) <= FREELO)
         {
             a->xfree = 1;
         }
         if (fabs(a->accelerationYdouble) <= FREELO)
         {
             a->yfree = 1;
         }
         if (fabs(a->accelerationZdouble) <= FREELO)
         {
             a->zfree = 1;
         }
         if (a->xfree == 1 && a->yfree == 1 && a->zfree == 1)
         {
             gtk_label_set_label((GtkLabel*)a->label[15], "<span foreground='white' background='red' weight='ultrabold' font='20'> FALL </span>");
             a->freeFallLabel = FALSE;
             g_timeout_add (FREEFALLTIME, (GSourceFunc) freeFallLabel, (gpointer) a);
         }
     }
 }
readRadioUSB()
void readRadioUSB (GtkWidget * button, gpointer * data)
read radio buttons for UART connection
Definition at line 220 of file menucallbacks.c.
References widgets::bufferStatusBar, direction::i, widgets::id, widgets::radioButtonUSBstate, widgets::radioUSB, and widgets::statusBar.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     gboolean r[5];
     gint i = 0;
     for (i = 0; i < 5; i++)
     {
         r[i] = FALSE;
     }
     for (i = 0; i < 5; i++)
     {
         r[i] = gtk_toggle_button_get_active (GTK_TOGGLE_BUTTON (a->radioUSB[i]));
     }
     if (r[0] == TRUE)
     {
         a->radioButtonUSBstate = 16;
         g_sprintf (a->bufferStatusBar, "you have chosen /dev/ttyUSB0, ID %d - please now press connect", a->radioButtonUSBstate);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
     else if (r[1] == TRUE)
     {
         a->radioButtonUSBstate = 17;
         g_sprintf (a->bufferStatusBar, "you have chosen /dev/ttyUSB1, ID %d - please now press connect", a->radioButtonUSBstate);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
     else if (r[2] == TRUE)
     {
         a->radioButtonUSBstate = 18;
         g_sprintf (a->bufferStatusBar, "you have chosen /dev/ttyUSB2, ID %d - please now press connect", a->radioButtonUSBstate);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
     else if (r[3] == TRUE)
     {
         a->radioButtonUSBstate = 19;
         g_sprintf (a->bufferStatusBar, "you have chosen /dev/ttyUSB3, ID %d - please now press connect", a->radioButtonUSBstate);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
     else
     {
         a->radioButtonUSBstate = 20;
         g_sprintf (a->bufferStatusBar, "you have chosen /dev/ttyUSB4, ID %d - please now press connect", a->radioButtonUSBstate);
         gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     }
 }
requestData()
void requestData (gpointer data)
function request data from XMC UART
Definition at line 551 of file menucallbacks.c.
References widgets::radioButtonUSBstate, RS232_flushTX(), RS232_SendBuf(), and RS232_SendByte().
Referenced by waitSendnoTerminal(), waitSendPython(), and waitSendTerminal().
 {
     widgets *a = (widgets *) data;
     unsigned char requestText[] = "#REQ,";
     RS232_flushTX(a->radioButtonUSBstate);
     RS232_SendBuf(a->radioButtonUSBstate, requestText, (int)sizeof(requestText));
     RS232_SendByte(a->radioButtonUSBstate, '\r');
 }
safeClose()
guint safeClose (gpointer data)
timer for safe UART close
Definition at line 455 of file menucallbacks.c.
References widgets::bufferStatusBar, widgets::button, widgets::entry, direction::i, widgets::id, widgets::radioButtonUSBstate, widgets::radioUSB, RS232_CloseComport(), widgets::safeWaitClose, and widgets::statusBar.
Referenced by safeEnd().
 {
     widgets *a = (widgets *) data;
     const char closeComPortSuccess[] = "SUCCESS closing COM port";
     gint i = 0;
     RS232_CloseComport(a->radioButtonUSBstate);
     snprintf(a->bufferStatusBar, sizeof(closeComPortSuccess)+1, "%s", closeComPortSuccess);
     gtk_statusbar_push (GTK_STATUSBAR (a->statusBar), a->id, a->bufferStatusBar);
     gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[3]), FALSE);
     gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[6]), FALSE);
     gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[7]), FALSE);
     gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[8]), FALSE);
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[0]), TRUE);
     for (i = 1; i < 7; i++)
     {
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[i]), FALSE);
     }
     gtk_widget_set_sensitive (GTK_WIDGET (a->entry[0]), TRUE);
     for (i = 0; i < 5; i++)
     {
         gtk_widget_set_sensitive (GTK_WIDGET (a->radioUSB[i]), TRUE);
     }
     return a->safeWaitClose;
 }
safeEnd()
guint safeEnd (gpointer data)
timer for safe UART end
Definition at line 435 of file menucallbacks.c.
References widgets::radioButtonUSBstate, RS232_flushTX(), RS232_SendBuf(), RS232_SendByte(), safeClose(), widgets::safeWaitClose, widgets::servoState, and UARTWAIT.
Referenced by safeStop().
 {
     widgets *a = (widgets *) data;
     unsigned char requestStop[] = "#END,";
     a->servoState = 0;
     RS232_flushTX(a->radioButtonUSBstate);
     RS232_SendBuf(a->radioButtonUSBstate, requestStop, (int)sizeof(requestStop));
     RS232_SendByte(a->radioButtonUSBstate, '\r');
     a->safeWaitClose = FALSE;
     g_timeout_add (UARTWAIT, (GSourceFunc) safeClose, (gpointer) a);
     return a->safeEnd;
 }
safeStop()
guint safeStop (gpointer data)
timer for safe UART stop
Definition at line 415 of file menucallbacks.c.
References widgets::radioButtonUSBstate, RS232_flushTX(), RS232_SendBuf(), RS232_SendByte(), widgets::safeEnd, safeEnd(), widgets::servoState, and UARTWAIT.
Referenced by connectSerial(), and quit().
 {
     widgets *a = (widgets *) data;
     unsigned char requestServoOff[] = "#SER,f";
     a->servoState = 0;
     RS232_flushTX(a->radioButtonUSBstate);
     RS232_SendBuf(a->radioButtonUSBstate, requestServoOff, (int)sizeof(requestServoOff));
     RS232_SendByte(a->radioButtonUSBstate, '\r');
     a->safeEnd = FALSE;
     g_timeout_add (UARTWAIT, (GSourceFunc) safeEnd, (gpointer) a);
     return a->safeWaitStop;
 }
saveData()
void saveData (GtkButton * button, gpointer data)
function to toggle protocol on off
Definition at line 835 of file menucallbacks.c.
References widgets::saveOutgoing.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(button)))
     {
         a->saveOutgoing = 1;
     }
     else
     {
         a->saveOutgoing = 0;
     }
 }
servo()
void servo (GtkWidget * button, gpointer data)
function toggle servo on off
Definition at line 656 of file menucallbacks.c.
References widgets::button, servoConnector(), and widgets::servoState.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(button)))
     {
         g_print("%s toggled on\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[6]), "SERVO on");
         a->servoState = 0;
     }
     else
     {
         g_print("%s toggled off\n", gtk_button_get_label(GTK_BUTTON(button)));
         gtk_button_set_label(GTK_BUTTON(a->button[6]), "SERVO off");
         a->servoState = 1;
     }
     servoConnector((gpointer) a);
 }
servoConnector()
void servoConnector (gpointer data)
function servo connector
Definition at line 565 of file menucallbacks.c.
References widgets::button, widgets::radioButtonUSBstate, RS232_flushTX(), RS232_SendBuf(), RS232_SendByte(), widgets::sendSerial, widgets::servoState, and widgets::transmission.
Referenced by servo().
 {
     widgets *a = (widgets *) data;
     unsigned char requestServoOn[] = "#SER,n";
     unsigned char requestServoOff[] = "#SER,f";
     a->sendSerial = FALSE;
     gtk_widget_set_sensitive (GTK_WIDGET (a->button[2]), FALSE);
     if (a->servoState == 0)
     {
         a->servoState = 1;
         RS232_flushTX(a->radioButtonUSBstate);
         RS232_SendBuf(a->radioButtonUSBstate, requestServoOn, (int)sizeof(requestServoOn));
         RS232_SendByte(a->radioButtonUSBstate, '\r');
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[8]), TRUE);
     }
     else if (a->servoState == 1)
     {
         a->servoState = 0;
         RS232_flushTX(a->radioButtonUSBstate);
         RS232_SendBuf(a->radioButtonUSBstate, requestServoOff, (int)sizeof(requestServoOff));
         RS232_SendByte(a->radioButtonUSBstate, '\r');
         gtk_widget_set_sensitive (GTK_WIDGET (a->button[8]), FALSE);
     }
     if (a->transmission == TRUE)
     {
         a->sendSerial = TRUE;
     }
 }
statisticConnector()
void statisticConnector (GtkButton * button, gpointer data)
function statistic request from XMC
Definition at line 635 of file menucallbacks.c.
References widgets::radioButtonUSBstate, RS232_flushTX(), RS232_SendBuf(), RS232_SendByte(), widgets::sendSerial, and widgets::transmission.
Referenced by constructGUI().
 {
     widgets *a = (widgets *) data;
     unsigned char requestStat[] = "#STA,";
     a->sendSerial = FALSE;
     RS232_flushTX(a->radioButtonUSBstate);
     RS232_SendBuf(a->radioButtonUSBstate, requestStat, (int)sizeof(requestStat));
     RS232_SendByte(a->radioButtonUSBstate, '\r');
     if (a->transmission == TRUE)
     {
         a->sendSerial = TRUE;
     }
 }
wait()
guint wait (gpointer data)
simple wait function button feedback XMC
Definition at line 274 of file menucallbacks.c.
References widgets::button, widgets::buttonID, widgets::sendSerial, widgets::transmission, and widgets::wait.
Referenced by rawProtocolDataTimed().
 {
     widgets *a = (widgets *) data;
     a->sendSerial = FALSE;
     if(a->buttonID == 1)
     {
         if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(a->button[6])) == TRUE)
         {
             gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[6]), FALSE);
         }
         else
         {
             gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[6]), TRUE);
         }
     }
     else if(a->buttonID == 2)
     {
         if (gtk_toggle_button_get_active(GTK_TOGGLE_BUTTON(a->button[8])) == TRUE)
         {
             gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[8]), FALSE);
         }
         else
         {
             gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(a->button[8]), TRUE);
         }
     }
     if (a->transmission == TRUE)
     {
         a->sendSerial = TRUE;
     }
     return a->wait;
 }
waitSendnoTerminal()
guint waitSendnoTerminal (gpointer data)
timer for output and request function
Definition at line 388 of file menucallbacks.c.
References rawProtocolDataTimed(), and requestData().
Referenced by dataTransmission().
 {
     widgets *a = (widgets *) data;
     requestData((gpointer) a);
     rawProtocolDataTimed((gpointer) a);
     return a->sendSerial;
 }
waitSendPython()
guint waitSendPython (gpointer data)
timer for output and request function Python
Definition at line 402 of file menucallbacks.c.
References requestData().
Referenced by pythonConnector(), and pythonSpriteConnector().
 {
     widgets *a = (widgets *) data;
     requestData((gpointer) a);
     return a->sendSerial;
 }
waitSendTerminal()
guint waitSendTerminal (gpointer data)
timer for output and request terminal function
Definition at line 365 of file menucallbacks.c.
References widgets::line, OSBUFFER, rawProtocolDataTimed(), and requestData().
Referenced by rawProtocolData().
 {
     widgets *a = (widgets *) data;
     char lineWithLF[OSBUFFER+1];
     g_sprintf(lineWithLF, "%s\n", a->line);
     requestData((gpointer) a);
     rawProtocolDataTimed((gpointer) a);
     gtk_text_buffer_get_start_iter (a->buffer, &a->iter);
     gtk_text_buffer_insert (a->buffer, &a->iter, lineWithLF, -1);
     gtk_text_buffer_get_bounds (a->buffer, &a->start, &a->end);
     gtk_text_buffer_apply_tag_by_name (a->buffer, "word_wrap", &a->start, &a->end);
     gtk_text_buffer_apply_tag_by_name (a->buffer, "not_editable", &a->start, &a->end);
     return a->sendSerial;
 }