BEL3 ESS task: gtk_GUI/rs232.h File Reference
rs232.h File Reference
#include <stdio.h>
#include <string.h>
#include <windows.h>
Functions
int RS232_OpenComport (int, int, const char *)
int RS232_PollComport (int, unsigned char *, int)
int RS232_SendByte (int, unsigned char)
int RS232_SendBuf (int, unsigned char *, int)
void RS232_CloseComport (int)
void RS232_cputs (int, const char *)
int RS232_IsDCDEnabled (int)
int RS232_IsCTSEnabled (int)
int RS232_IsDSREnabled (int)
void RS232_enableDTR (int)
void RS232_disableDTR (int)
void RS232_enableRTS (int)
void RS232_disableRTS (int)
void RS232_flushRX (int)
void RS232_flushTX (int)
void RS232_flushRXTX (int)
int RS232_GetPortnr (const char *)
Function Documentation
RS232_CloseComport()
void RS232_CloseComport (int)
Definition at line 761 of file rs232.c.
Referenced by safeClose().
 {
     CloseHandle(Cport[comport_number]);
 }
RS232_cputs()
void RS232_cputs (int , const char *)
Definition at line 852 of file rs232.c.
References RS232_SendByte().
 {
     while(*text != 0)   RS232_SendByte(comport_number, *(text++));
 }
RS232_disableDTR()
void RS232_disableDTR (int)
Definition at line 809 of file rs232.c.
 {
     EscapeCommFunction(Cport[comport_number], CLRDTR);
 }
RS232_disableRTS()
void RS232_disableRTS (int)
Definition at line 821 of file rs232.c.
 {
     EscapeCommFunction(Cport[comport_number], CLRRTS);
 }
RS232_enableDTR()
void RS232_enableDTR (int)
Definition at line 803 of file rs232.c.
 {
     EscapeCommFunction(Cport[comport_number], SETDTR);
 }
RS232_enableRTS()
void RS232_enableRTS (int)
Definition at line 815 of file rs232.c.
 {
     EscapeCommFunction(Cport[comport_number], SETRTS);
 }
RS232_flushRX()
void RS232_flushRX (int)
Definition at line 830 of file rs232.c.
Referenced by rawProtocolDataTimed().
 {
     PurgeComm(Cport[comport_number], PURGE_RXCLEAR | PURGE_RXABORT);
 }
RS232_flushRXTX()
void RS232_flushRXTX (int)
Definition at line 842 of file rs232.c.
Referenced by constructGUI().
 {
     PurgeComm(Cport[comport_number], PURGE_RXCLEAR | PURGE_RXABORT);
     PurgeComm(Cport[comport_number], PURGE_TXCLEAR | PURGE_TXABORT);
 }
RS232_flushTX()
void RS232_flushTX (int)
Definition at line 836 of file rs232.c.
Referenced by connectSerial(), rawProtocolDataTimed(), requestData(), safeEnd(), safeStop(), servoConnector(), and statisticConnector().
 {
     PurgeComm(Cport[comport_number], PURGE_TXCLEAR | PURGE_TXABORT);
 }
RS232_GetPortnr()
int RS232_GetPortnr (const char *)
Definition at line 859 of file rs232.c.
References direction::i, and RS232_PORTNR.
 {
     int i;
     char str[32];
 #if defined(__linux__) || defined(__FreeBSD__)   /* Linux & FreeBSD */
     strcpy(str, "/dev/");
 #else  /* windows */
     strcpy(str, "\\\\.\\");
 #endif
     strncat(str, devname, 16);
     str[31] = 0;
     for(i=0; i<RS232_PORTNR; i++)
     {
         if(!strcmp(comports[i], str))
         {
             return i;
         }
     }
     return -1;  /* device not found */
 }
RS232_IsCTSEnabled()
int RS232_IsCTSEnabled (int)
Definition at line 781 of file rs232.c.
 {
     int status;
     GetCommModemStatus(Cport[comport_number], (LPDWORD)((void *)&status));
     if(status&MS_CTS_ON) return(1);
     else return(0);
 }
RS232_IsDCDEnabled()
int RS232_IsDCDEnabled (int)
Definition at line 770 of file rs232.c.
 {
     int status;
     GetCommModemStatus(Cport[comport_number], (LPDWORD)((void *)&status));
     if(status&MS_RLSD_ON) return(1);
     else return(0);
 }
RS232_IsDSREnabled()
int RS232_IsDSREnabled (int)
Definition at line 792 of file rs232.c.
 {
     int status;
     GetCommModemStatus(Cport[comport_number], (LPDWORD)((void *)&status));
     if(status&MS_DSR_ON) return(1);
     else return(0);
 }
RS232_OpenComport()
int RS232_OpenComport (int , int , const char *)
Definition at line 543 of file rs232.c.
References RS232_PORTNR.
Referenced by connectSerial().
 {
     if((comport_number>=RS232_PORTNR)||(comport_number<0))
     {
         printf("illegal comport number\n");
         return(1);
     }
     switch(baudrate)
     {
     case     110 :
         strcpy(mode_str, "baud=110");
         break;
     case     300 :
         strcpy(mode_str, "baud=300");
         break;
     case     600 :
         strcpy(mode_str, "baud=600");
         break;
     case    1200 :
         strcpy(mode_str, "baud=1200");
         break;
     case    2400 :
         strcpy(mode_str, "baud=2400");
         break;
     case    4800 :
         strcpy(mode_str, "baud=4800");
         break;
     case    9600 :
         strcpy(mode_str, "baud=9600");
         break;
     case   19200 :
         strcpy(mode_str, "baud=19200");
         break;
     case   38400 :
         strcpy(mode_str, "baud=38400");
         break;
     case   57600 :
         strcpy(mode_str, "baud=57600");
         break;
     case  115200 :
         strcpy(mode_str, "baud=115200");
         break;
     case  128000 :
         strcpy(mode_str, "baud=128000");
         break;
     case  256000 :
         strcpy(mode_str, "baud=256000");
         break;
     case  500000 :
         strcpy(mode_str, "baud=500000");
         break;
     case 1000000 :
         strcpy(mode_str, "baud=1000000");
         break;
     default      :
         printf("invalid baudrate\n");
         return(1);
         break;
     }
     if(strlen(mode) != 3)
     {
         printf("invalid mode \"%s\"\n", mode);
         return(1);
     }
     switch(mode[0])
     {
     case '8':
         strcat(mode_str, " data=8");
         break;
     case '7':
         strcat(mode_str, " data=7");
         break;
     case '6':
         strcat(mode_str, " data=6");
         break;
     case '5':
         strcat(mode_str, " data=5");
         break;
     default :
         printf("invalid number of data-bits '%c'\n", mode[0]);
         return(1);
         break;
     }
     switch(mode[1])
     {
     case 'N':
     case 'n':
         strcat(mode_str, " parity=n");
         break;
     case 'E':
     case 'e':
         strcat(mode_str, " parity=e");
         break;
     case 'O':
     case 'o':
         strcat(mode_str, " parity=o");
         break;
     default :
         printf("invalid parity '%c'\n", mode[1]);
         return(1);
         break;
     }
     switch(mode[2])
     {
     case '1':
         strcat(mode_str, " stop=1");
         break;
     case '2':
         strcat(mode_str, " stop=2");
         break;
     default :
         printf("invalid number of stop bits '%c'\n", mode[2]);
         return(1);
         break;
     }
     strcat(mode_str, " dtr=on rts=on");
     /*
     http://msdn.microsoft.com/en-us/library/windows/desktop/aa363145%28v=vs.85%29.aspx
     http://technet.microsoft.com/en-us/library/cc732236.aspx
     */
     Cport[comport_number] = CreateFileA(comports[comport_number],
                                         GENERIC_READ|GENERIC_WRITE,
                                         0,                          /* no share  */
                                         NULL,                       /* no security */
                                         OPEN_EXISTING,
                                         0,                          /* no threads */
                                         NULL);                      /* no templates */
     if(Cport[comport_number]==INVALID_HANDLE_VALUE)
     {
         printf("unable to open comport\n");
         return(1);
     }
     DCB port_settings;
     memset(&port_settings, 0, sizeof(port_settings));  /* clear the new struct  */
     port_settings.DCBlength = sizeof(port_settings);
     if(!BuildCommDCBA(mode_str, &port_settings))
     {
         printf("unable to set comport dcb settings\n");
         CloseHandle(Cport[comport_number]);
         return(1);
     }
     if(!SetCommState(Cport[comport_number], &port_settings))
     {
         printf("unable to set comport cfg settings\n");
         CloseHandle(Cport[comport_number]);
         return(1);
     }
     COMMTIMEOUTS Cptimeouts;
     Cptimeouts.ReadIntervalTimeout         = MAXDWORD;
     Cptimeouts.ReadTotalTimeoutMultiplier  = 0;
     Cptimeouts.ReadTotalTimeoutConstant    = 0;
     Cptimeouts.WriteTotalTimeoutMultiplier = 0;
     Cptimeouts.WriteTotalTimeoutConstant   = 0;
     if(!SetCommTimeouts(Cport[comport_number], &Cptimeouts))
     {
         printf("unable to set comport time-out settings\n");
         CloseHandle(Cport[comport_number]);
         return(1);
     }
     return(0);
 }
RS232_PollComport()
int RS232_PollComport (int , unsigned char * , int)
Definition at line 723 of file rs232.c.
Referenced by rawProtocolDataTimed().
 {
     int n;
     /* added the void pointer cast, otherwise gcc will complain about */
     /* "warning: dereferencing type-punned pointer will break strict aliasing rules" */
     ReadFile(Cport[comport_number], buf, size, (LPDWORD)((void *)&n), NULL);
     return(n);
 }
RS232_SendBuf()
int RS232_SendBuf (int , unsigned char * , int)
Definition at line 748 of file rs232.c.
Referenced by connectSerial(), requestData(), safeEnd(), safeStop(), servoConnector(), and statisticConnector().
 {
     int n;
     if(WriteFile(Cport[comport_number], buf, size, (LPDWORD)((void *)&n), NULL))
     {
         return(n);
     }
     return(-1);
 }
RS232_SendByte()
int RS232_SendByte (int , unsigned char)
Definition at line 736 of file rs232.c.
Referenced by connectSerial(), requestData(), RS232_cputs(), safeEnd(), safeStop(), servoConnector(), and statisticConnector().
 {
     int n;
     WriteFile(Cport[comport_number], &byte, 1, (LPDWORD)((void *)&n), NULL);
     if(n<0)  return(1);
     return(0);
 }