XMC4500 Barebone Template: inc/servo_library.h File Reference
servo_library.h File Reference
servo library header
#include "3Daccel_app.h"
#include "servo_driver.h"
Functions
void pwm (double dutycycle, uint8_t out)
set PWM for servos
void initServoPWM ()
init PWM for servos
Detailed Description
servo library header
Version
v1.0
Date
Nov 2017
Author
Egermann, Resch
Definition in file servo_library.h.
Function Documentation
initServoPWM()
void initServoPWM ()
init PWM for servos
Parameters
none
Returns
none
Definition at line 38 of file servo_library.c.
References initServoPWMXMC().
Referenced by main().
 {
     initServoPWMXMC();
 }
pwm()
void pwm (double dutycycle, uint8_t out)
set PWM for servos
Parameters
dutycycle in percent
0 for upper servo
1 for lower servo
Returns
none
Definition at line 20 of file servo_library.c.
References pwmXMC().
Referenced by main(), and SysTick_Handler().
 {
     if (out == 0)
     {
         pwmXMC(dutycycle, 0);
     }
     else
     {
         pwmXMC(dutycycle, 1);
     }
 }