BEL3 ESS task: src/servo_library.c File Reference
servo_library.c File Reference
servo library
#include "servo_library.h"
Functions
void initServoPWM ()
init PWM for servos
uint8_t pwm (double dutycycle, uint8_t out)
set PWM for servos
Detailed Description
servo library
Version
v1.0
Date
Jan 2018
Author
Egermann, Resch
Definition in file servo_library.c.
Function Documentation
initServoPWM()
void initServoPWM ()
init PWM for servos
Parameters
none
Returns
none
Definition at line 18 of file servo_library.c.
References initServoPWMXMC().
Referenced by main().
 {
     // init servos
     initServoPWMXMC();
 }
pwm()
uint8_t pwm (double dutycycle, uint8_t out)
set PWM for servos
Parameters
dutycycle in percent
0 for upper servo
1 for lower servo
Returns
none
Definition at line 33 of file servo_library.c.
References pwmXMC().
Referenced by main(), and SysTick_Handler().
 {
     // call pwm driver
     if (out == 0)
     {
         if(pwmXMC(dutycycle, 0) == 0)
         {
             return 0;
         }
         else
         {
             return 1;
         }
     }
     else
     {
         if(pwmXMC(dutycycle, 1) == 0)
         {
             return 0;
         }
         else
         {
             return 1;
         }
     }
 }