BEL3 ESS task: inc/xmc4500_i2c_lib.h File Reference
xmc4500_i2c_lib.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <xmc_i2c.h>
#include <xmc_gpio.h>
#include <xmc_usic.h>
Macros
#define LIS3DH_ADR 0x18
#define LIS3DH_RD_ADR (LIS3DH_ADR<<1)
Functions
uint8_t _init_i2c1_ch0 (void)
This function configures the I2C interface to communicate via pins P0_5 & P0_11.
uint8_t _i2c_xfer (uint8_t id, uint8_t reg_addr, uint8_t i2c_data, _Bool rd_wr)
This function writes/reads data to a specific I2C channel.
Macro Definition Documentation
LIS3DH_ADR
#define LIS3DH_ADR 0x18
Definition at line 19 of file xmc4500_i2c_lib.h.
LIS3DH_RD_ADR
#define LIS3DH_RD_ADR (LIS3DH_ADR<<1)
Definition at line 20 of file xmc4500_i2c_lib.h.
Referenced by _i2c_xfer().
Function Documentation
_i2c_xfer()
uint8_t _i2c_xfer (uint8_t id, uint8_t reg_addr, uint8_t i2c_data, _Bool rd_wr)
This function writes/reads data to a specific I2C channel.
Parameters
id ... I2C device ID reg_addr ... I2C register address of the device i2c_data ... I2C data value rd_wr ... I2C Read/Write direction
Returns
read-value on a I2C read request or return write-value on I2C write request
Definition at line 53 of file xmc4500_i2c_lib.c.
References LIS3DH_RD_ADR.
Referenced by LIS3DH_ReadReg(), and LIS3DH_WriteReg().
 {
     XMC_USIC_CH_t *channel;
     char _tmp_i2c_recv_ = 0;
     uint8_t id_tmp = 0;
     channel = XMC_I2C1_CH0;
     id_tmp = LIS3DH_RD_ADR;
     XMC_I2C_CH_MasterStart (channel, id_tmp, XMC_I2C_CH_CMD_WRITE);
     while ( (XMC_I2C_CH_GetStatusFlag (channel) & XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED) == 0U) {
         /* wait for ACK */
     }
     XMC_I2C_CH_ClearStatusFlag (channel, XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED);
     XMC_I2C_CH_MasterTransmit (channel, reg_addr);
     while ( (XMC_I2C_CH_GetStatusFlag (channel) & XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED) == 0U) {
         /* wait for ACK */
     }
     XMC_I2C_CH_ClearStatusFlag (channel, XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED);
     if (rd_wr) {
         /* Read from REG */
         XMC_I2C_CH_MasterRepeatedStart (channel, id_tmp, XMC_I2C_CH_CMD_READ);
         while ( (XMC_I2C_CH_GetStatusFlag (channel) & XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED) == 0U) {
             /* wait for ACK */
         }
         XMC_I2C_CH_ClearStatusFlag (channel, XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED);
         XMC_I2C_CH_MasterReceiveNack (channel);
         while ( (XMC_USIC_CH_GetReceiveBufferStatus (channel) !=
                  (uint32_t) XMC_USIC_CH_RBUF_STATUS_DATA_VALID1) && ( (uint32_t) XMC_USIC_CH_GetReceiveBufferStatus (channel)
                          != (uint32_t) XMC_USIC_CH_RBUF_STATUS_DATA_VALID0));
         _tmp_i2c_recv_ = XMC_I2C_CH_GetReceivedData (channel);
         XMC_I2C_CH_MasterStop (channel);
         return _tmp_i2c_recv_;
     } else {
         /* Write to REG */
         XMC_I2C_CH_MasterTransmit (channel, i2c_data);
         while ( (XMC_I2C_CH_GetStatusFlag (channel) & XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED) == 0U) {
             /* wait for ACK */
         }
         XMC_I2C_CH_ClearStatusFlag (channel, XMC_I2C_CH_STATUS_FLAG_ACK_RECEIVED);
         XMC_I2C_CH_MasterStop (channel);
         return i2c_data;
     }
 }
_init_i2c1_ch0()
uint8_t _init_i2c1_ch0 (void)
This function configures the I2C interface to communicate via pins P0_5 & P0_11.
Parameters
none
Returns
on success this function returns 0
Definition at line 31 of file xmc4500_i2c_lib.c.
References i2c_cfg, i2c_scl, and i2c_sda.
Referenced by main().
 {
     XMC_I2C_CH_Init (XMC_I2C1_CH0, &i2c_cfg);
     XMC_I2C_CH_SetInputSource (XMC_I2C1_CH0, XMC_I2C_CH_INPUT_SDA, USIC1_C0_DX0_P0_5);
     XMC_I2C_CH_SetInputSource (XMC_I2C1_CH0, XMC_I2C_CH_INPUT_SCL, USIC1_C0_DX1_SCLKOUT);
     XMC_I2C_CH_Start (XMC_I2C1_CH0);
     XMC_GPIO_Init (P0_11, &i2c_scl);
     XMC_GPIO_Init (P0_5, &i2c_sda);
     return 0;
 }