BEL3 ESS task: inc/xmc4500_uart_lib.h File Reference
xmc4500_uart_lib.h File Reference
Functions
void _init_uart0_ch0 (void)
uint8_t _uart_send_char (char c)
uint8_t _uart_printf (char *fmt,...)
uint8_t _uart_send_string (char *str)
uint8_t _uart_get_string (char *str)
Function Documentation
_init_uart0_ch0()
void _init_uart0_ch0 (void)
Definition at line 48 of file xmc4500_uart_lib.c.
References RX_FIFO_INITIAL_LIMIT, TX_FIFO_INITIAL_LIMIT, uart_config, UART_RX, uart_rx, UART_TX, and uart_tx.
Referenced by main().
 {
     /* USIC channels initialization */
     XMC_UART_CH_Init (XMC_UART0_CH0, &uart_config);
     XMC_UART_CH_SetInputSource (XMC_UART0_CH0, XMC_UART_CH_INPUT_RXD,
                                 USIC0_C0_DX0_P1_4);
     /* FIFOs initialization for both channels:
      *  8 entries for TxFIFO from point 0, LIMIT=1
      *  8 entries for RxFIFO from point 8, LIMIT=7 (SRBI is set if all 8*data have
      *                                              been received)
      *  */
     XMC_USIC_CH_TXFIFO_Configure (XMC_UART0_CH0, 0, XMC_USIC_CH_FIFO_SIZE_8WORDS, TX_FIFO_INITIAL_LIMIT);
     XMC_USIC_CH_RXFIFO_Configure (XMC_UART0_CH0, 8, XMC_USIC_CH_FIFO_SIZE_8WORDS, RX_FIFO_INITIAL_LIMIT);
     /* Enabling events for TX FIFO and RX FIFO */
     XMC_USIC_CH_RXFIFO_EnableEvent (XMC_UART0_CH0,
                                     XMC_USIC_CH_RXFIFO_EVENT_CONF_STANDARD |
                                     XMC_USIC_CH_RXFIFO_EVENT_CONF_ALTERNATE);
     /* Connecting the previously enabled events to a Service Request line number */
     XMC_USIC_CH_RXFIFO_SetInterruptNodePointer (XMC_UART0_CH0, XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_STANDARD, 0);
     XMC_USIC_CH_RXFIFO_SetInterruptNodePointer (XMC_UART0_CH0, XMC_USIC_CH_RXFIFO_INTERRUPT_NODE_POINTER_ALTERNATE, 0);
     /* Start USIC operation as UART */
     XMC_UART_CH_Start (XMC_UART0_CH0);
     /*Initialization of the necessary ports*/
     XMC_GPIO_Init (UART_TX, &uart_tx);
     XMC_GPIO_Init (UART_RX, &uart_rx);
     /* Configuring priority and enabling NVIC IRQ for the defined service request
     line number */
     NVIC_SetPriority (USIC0_0_IRQn, 63U);
     NVIC_EnableIRQ (USIC0_0_IRQn);
     return;
 }
_uart_get_string()
uint8_t _uart_get_string (char * str)
Definition at line 144 of file xmc4500_uart_lib.c.
References BUFFER_SIZE_RX, ERR_OUT_OF_MEMORY, rx_buffer, and str_available.
Referenced by main().
 {
     if (str == NULL) {
         return ERR_OUT_OF_MEMORY;
     }
     while (!str_available);
     memcpy (str, &rx_buffer, strlen (rx_buffer));
     memset (&rx_buffer, 0x00, BUFFER_SIZE_RX);
     str_available = false;
     return 0;
 }
_uart_printf()
uint8_t _uart_printf (char * fmt, ...)
Definition at line 114 of file xmc4500_uart_lib.c.
References _uart_send_string(), BUFFER_SIZE_PRINTF, and ERR_OUT_OF_MEMORY.
Referenced by protocolComplete().
 {
     va_list arg_ptr;
     char buffer[BUFFER_SIZE_PRINTF];
     if (fmt == NULL)  {
         return ERR_OUT_OF_MEMORY;
     }
     va_start (arg_ptr, fmt);
     vsprintf (buffer, fmt, arg_ptr);
     va_end (arg_ptr);
     _uart_send_string (buffer);
     return 0;
 }
_uart_send_char()
uint8_t _uart_send_char (char c)
Definition at line 106 of file xmc4500_uart_lib.c.
 {
     while (XMC_USIC_CH_GetTransmitBufferStatus (XMC_UART0_CH0) == XMC_USIC_CH_TBUF_STATUS_BUSY);
     XMC_UART_CH_Transmit (XMC_UART0_CH0, c);
     return 0;
 }
_uart_send_string()
uint8_t _uart_send_string (char * str)
Definition at line 131 of file xmc4500_uart_lib.c.
References ERR_OUT_OF_MEMORY, and direction::i.
Referenced by _uart_printf().
 {
     if (str == NULL) {
         return ERR_OUT_OF_MEMORY;
     }
     for (int i = 0; i < strlen (str); i++) {
         while (XMC_USIC_CH_GetTransmitBufferStatus (XMC_UART0_CH0) == XMC_USIC_CH_TBUF_STATUS_BUSY);
         XMC_UART_CH_Transmit (XMC_UART0_CH0, str[i]);
     }
     return 0;
 }